with open('automation/launch_checker.py', 'r', encoding='utf-8') as f:
    lines = f.readlines()

start = 37
end = 116
replacement = [
    '    def sync_prices():\n',
    '        print("Starting Price Sync...")\n',
    '        if not os.path.exists(LOG_FILE):\n',
    '            with open(LOG_FILE, "w") as f:\n',
    '                f.write("timestamp,product,brand,old_price,new_price,diff,direction,source\\n")\n',
    '        products = fetch_all_products()\n',
    '        updated_count = 0\n',
    '\n',
    '        print(f"Found {len(products)} products in Sanity")\n',
    '        checked = 0\n',
    '        skipped_no_url = 0\n',
    '        skipped_no_price = 0\n',
    '        matched = 0\n',
    '\n',
    '        for product in products:\n',
    '            source = get_assigned_source(product)\n',
    '            brand = (product.get("brand") or {}).get("name", "")\n',
    '            if source is None:\n',
    '                continue\n',
    '\n',
    '            flipkart_url = product.get("flipkartUrl")\n',
    '            amazon_url = product.get("amazonUrl")\n',
    '            old_price = product.get("price")\n',
    '\n',
    '            checked += 1\n',
    '            amz_price = None\n',
    '            flip_price = None\n',
    '            display_price = None\n',
    '\n',
    '            if source == "flipkart":\n',
    '                if not flipkart_url:\n',
    '                    skipped_no_url += 1\n',
    '                    print(f" SKIP {product[\'name\']}: no flipkartUrl")\n',
    '                    continue\n',
    '                flip_price = get_flipkart_price(flipkart_url)\n',
    '                display_price = flip_price\n',
    '            elif source == "amazon":\n',
    '                if not amazon_url:\n',
    '                    skipped_no_url += 1\n',
    '                    print(f" SKIP {product[\'name\']}: no amazonUrl")\n',
    '                    continue\n',
    '                amz_price = get_amazon_price(amazon_url)\n',
    '                display_price = amz_price\n',
    '            elif source == "both":\n',
    '                flip_price = get_flipkart_price(flipkart_url) if flipkart_url else None\n',
    '                amz_price = get_amazon_price(amazon_url) if amazon_url else None\n',
    '                prices = [p for p in [amz_price, flip_price] if p is not None]\n',
    '                if not prices:\n',
    '                    print(f" SKIP {product[\'name\']}: both scrapers returned None")\n',
    '                    skipped_no_price += 1\n',
    '                    continue\n',
    '                display_price = min(prices)\n',
    '\n',
    '            if display_price is None:\n',
    '                print(f" SKIP {product[\'name\']}: scraper returned None (old={old_price})")\n',
    '                skipped_no_price += 1\n',
    '                continue\n',
    '\n',
    '            if old_price not in (None, 0):\n',
    '                change = abs(display_price - old_price) / old_price\n',
    '                if change > 0.5:\n',
    '                    print(f" SKIP {product[\'name\']}: suspicious price change (₹{old_price} → ₹{display_price})")\n',
    '                    skipped_no_price += 1\n',
    '                    continue\n',
    '\n',
    '            if old_price == display_price:\n',
    '                matched += 1\n',
    '                print(f" = {product[\'name\']} ({brand}): ₹{old_price} (unchanged)")\n',
    '                continue\n',
    '\n',
    '            update_price(product["_id"], amz_price, flip_price, display_price)\n',
    '            updated_count += 1\n',
    '            diff = display_price - (old_price or 0)\n',
    '            arrow = "UP" if diff > 0 else "DOWN"\n',
    '            log_change(product["name"], brand, old_price, display_price, source)\n',
    '            print(f" {arrow} {product[\'name\']} ({brand}): ₹{old_price} → ₹{display_price} ({\'+\' if diff > 0 else \'\'}{diff}) via {source}")\n',
    '\n',
    '        print(f"✓ Checked {checked} phones. Updated {updated_count}. Matched {matched}. No URL: {skipped_no_url}. Scrape failed: {skipped_no_price}.")\n',
    '\n',
    '\n',
    '\n',
]

lines = lines[: start - 1] + replacement + lines[end:]
with open('automation/launch_checker.py', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print('done')
