import { readFileSync, writeFileSync } from "node:fs";
import { products } from "../src/lib/data/products";
import {
  DEFAULT_DIRECT_URLS_CSV_PATH,
  parseDirectUrlsCsv,
  matchSlugs,
  findSearchUrls,
} from "../src/lib/data/direct-urls-parse";

const sourcePath =
  process.argv.find((arg) => arg.startsWith("--in="))?.slice("--in=".length) ||
  DEFAULT_DIRECT_URLS_CSV_PATH;

const csv = readFileSync(sourcePath, "utf8");
const aggregated = parseDirectUrlsCsv(csv);

const slugMatch = matchSlugs(
  aggregated,
  products.map((p) => p.slug),
  products.map((p) => p.name),
);

const matchedProducts = slugMatch.matched.map((m) => m.product);
const searchUrls = findSearchUrls(matchedProducts);

const bySlug: Record<string, (typeof matchedProducts)[number]> = {};
for (const m of slugMatch.matched) {
  const p = m.product;
  bySlug[m.slug] = {
    brand: p.brand,
    name: p.name,
    colorNames: p.colorNames,
    variants: p.variants,
    amazonUrl: p.amazonUrl,
    flipkartUrl: p.flipkartUrl,
  };
}

const totalVariants = matchedProducts.reduce((n, p) => n + p.variants.length, 0);

const meta = {
  generatedAt: new Date().toISOString(),
  source: sourcePath,
  matched: slugMatch.matched.length,
  unknown: slugMatch.unknown,
  searchUrls,
  totalVariants,
};

const out =
  `// AUTO-GENERATED by scripts/build-direct-urls-data.ts from ${sourcePath}\n` +
  `// Do not edit by hand. Re-run \`npm run direct-urls:build\` to regenerate.\n` +
  `import type { DirectUrlProduct } from "./direct-urls-parse";\n\n` +
  `export const DIRECT_URLS_BY_SLUG: Record<string, DirectUrlProduct> = ` +
  JSON.stringify(bySlug, null, 2) +
  `;\n\n` +
  `export const DIRECT_URLS_META = ${JSON.stringify(meta, null, 2)};\n`;

writeFileSync("src/lib/data/direct-urls-data.ts", out);

console.log(`matched=${slugMatch.matched.length} unknown=${slugMatch.unknown.length} totalVariants=${totalVariants}`);
if (slugMatch.unknown.length > 0) {
  console.log(`UNKNOWN: ${slugMatch.unknown.join(" | ")}`);
}
if (searchUrls.length > 0) {
  console.warn(`WARNING: ${searchUrls.length} search URLs found (expected direct product pages):`);
  for (const u of searchUrls.slice(0, 10)) console.warn(`  ${u}`);
}
