// AUTO-GENERATED by scripts/build-direct-urls-data.ts from C:\Users\ramak\Downloads\products_with_direct_urls.csv
// Do not edit by hand. Re-run `npm run direct-urls:build` to regenerate.
import type { DirectUrlProduct } from "./direct-urls-parse";

export const DIRECT_URLS_BY_SLUG: Record<string, DirectUrlProduct> = {
  "airpods-4": {
    "brand": "Apple",
    "name": "Apple AirPods 4",
    "colorNames": [
      "White"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 12900,
        "flipkartUrl": "https://www.flipkart.com/apple-airpods-4-wireless-earbuds-personalised-spatial-audio-sweat-water-resistant-bluetooth/p/itmdf102348be4b9",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/apple-airpods-4-wireless-earbuds-personalised-spatial-audio-sweat-water-resistant-bluetooth/p/itmdf102348be4b9"
  },
  "iphone-17": {
    "brand": "Apple",
    "name": "iPhone 17",
    "colorNames": [
      "Lavender",
      "Sage",
      "Mist Blue",
      "White",
      "Black"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 79900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-black-256-gb/p/itm6eb39da622cdd",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 6000,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-deep-blue-512-gb/p/itmce30d684c921a",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-black-256-gb/p/itm6eb39da622cdd"
  },
  "iphone-17-air": {
    "brand": "Apple",
    "name": "iPhone 17 Air",
    "colorNames": [
      "Sky Blue",
      "Light Gold",
      "Cloud White",
      "Space Black"
    ],
    "variants": [
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 75905,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-black-256-gb/p/itm6eb39da622cdd",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 113900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-air-sky-blue-512-gb/p/itmcedc5bee26cc9",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "1 TB",
        "price": 135900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-air-space-black-1-tb/p/itm5f6f4dba722bd",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-black-256-gb/p/itm6eb39da622cdd"
  },
  "iphone-17-pro": {
    "brand": "Apple",
    "name": "iPhone 17 Pro",
    "colorNames": [
      "Cosmic Orange",
      "Deep Blue",
      "Silver"
    ],
    "variants": [
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 119900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-cosmic-orange-256-gb/p/itm76fe37ca9ea8c",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 119900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-cosmic-orange-512-gb/p/itm999d978f08430",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "1 TB",
        "price": 178900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-max-silver-1-tb/p/itm769146f0d9528",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-cosmic-orange-256-gb/p/itm76fe37ca9ea8c"
  },
  "iphone-17-pro-max": {
    "brand": "Apple",
    "name": "iPhone 17 Pro Max",
    "colorNames": [
      "Silver",
      "Cosmic Orange",
      "Deep Blue"
    ],
    "variants": [
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 138900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-max-cosmic-orange-256-gb/p/itmd38e30731883a",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 138900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-deep-blue-512-gb/p/itmce30d684c921a",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "1 TB",
        "price": 178900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-max-silver-1-tb/p/itm769146f0d9528",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "2 TB",
        "price": 218900,
        "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-max-deep-blue-2-tb/p/itm5ca66177b1b9e",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/apple-iphone-17-pro-max-cosmic-orange-256-gb/p/itmd38e30731883a"
  },
  "pixel-10": {
    "brand": "Google",
    "name": "Google Pixel 10",
    "colorNames": [
      "Indigo",
      "Frost",
      "Lemongrass",
      "Obsidian"
    ],
    "variants": [
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 69999,
        "flipkartUrl": "https://www.flipkart.com/google-pixel-10-frost-256-gb/p/itm180af25bcc197",
        "verified": false
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 69999,
        "flipkartUrl": "https://www.flipkart.com/google-pixel-10-frost-256-gb/p/itm180af25bcc197",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/google-pixel-10-frost-256-gb/p/itm180af25bcc197"
  },
  "pixel-10a": {
    "brand": "Google",
    "name": "Google Pixel 10a",
    "colorNames": [
      "Obsidian",
      "Porcelain",
      "Aloe",
      "Bay"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 49999,
        "flipkartUrl": "https://www.flipkart.com/google-pixel-10a-lavender-256-gb/p/itmba3073a0f391e",
        "verified": false
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 49999,
        "flipkartUrl": "https://www.flipkart.com/google-pixel-10a-lavender-256-gb/p/itmba3073a0f391e",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/google-pixel-10a-lavender-256-gb/p/itmba3073a0f391e"
  },
  "hmd-vibe-2": {
    "brand": "HMD",
    "name": "HMD Vibe 2",
    "colorNames": [
      "Cosmic Lavender",
      "Nordic Blue",
      "Peach Pink"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 17099,
        "flipkartUrl": "https://www.flipkart.com/hmd-vibe2-5g-cosmic-lavender-64-gb/p/itm71c3ae6df2a26",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 8074,
        "flipkartUrl": "https://www.flipkart.com/hmd-vibe-5g-black-128-gb/p/itm3279bb5058357",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 17099,
        "flipkartUrl": "https://www.flipkart.com/hmd-vibe2-5g-cosmic-lavender-64-gb/p/itm71c3ae6df2a26",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 8074,
        "flipkartUrl": "https://www.flipkart.com/hmd-vibe-5g-black-128-gb/p/itm3279bb5058357",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/hmd-vibe2-5g-cosmic-lavender-64-gb/p/itm71c3ae6df2a26"
  },
  "infinix-gt-30": {
    "brand": "Infinix",
    "name": "Infinix GT 30",
    "colorNames": [
      "Pulse Green",
      "Cyber Blue",
      "Blade White"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 17999,
        "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-5g-cyber-blue-128-cyber-blue-gb/p/itmcda81613113c6",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 1055,
        "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-blade-white-256-gb/p/itmd4bc1852572b9",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-5g-cyber-blue-128-cyber-blue-gb/p/itmcda81613113c6"
  },
  "infinix-gt-30-pro": {
    "brand": "Infinix",
    "name": "Infinix GT 30 Pro",
    "colorNames": [
      "Dark Flare",
      "Blade White",
      "Shadow Ash"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 1055,
        "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-dark-flare-256-gb/p/itmd4bc1852572b9",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-dark-flare-256-gb/p/itmd4bc1852572b9",
        "verified": false
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 1055,
        "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-dark-flare-256-gb/p/itmd4bc1852572b9",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-dark-flare-256-gb/p/itmd4bc1852572b9",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-dark-flare-256-gb/p/itmd4bc1852572b9"
  },
  "infinix-note-edge": {
    "brand": "Infinix",
    "name": "Infinix Note Edge",
    "colorNames": [
      "Shadow Black",
      "Solar Orange",
      "Lunar Titanium",
      "Silk Green",
      "Stellar Blue"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/infinix-note-edge-silk-green-128-gb/p/itmab2876405a1ab",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/infinix-note-edge-solar-orange-256-gb/p/itm7720c4dde19f1",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/infinix-note-edge-silk-green-128-gb/p/itmab2876405a1ab"
  },
  "infinix-smart-10": {
    "brand": "Infinix",
    "name": "Infinix Smart 10",
    "colorNames": [
      "Black",
      "Blue",
      "Green"
    ],
    "variants": [
      {
        "ram": "3 GB",
        "storage": "64 GB",
        "price": 5999,
        "flipkartUrl": "https://www.flipkart.com/infinix-smart-10-titanium-silver-64-gb/p/itm0bde9cee1963a",
        "verified": true
      },
      {
        "ram": "3 GB",
        "storage": "128 GB",
        "price": 7799,
        "flipkartUrl": "https://www.flipkart.com/infinix-smart-8-plus-timber-black-128-gb/p/itmb71da75c376e1",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 5999,
        "flipkartUrl": "https://www.flipkart.com/infinix-smart-10-titanium-silver-64-gb/p/itm0bde9cee1963a",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 11999,
        "flipkartUrl": "https://www.flipkart.com/infinix-hot-10-ocean-wave-128-gb/p/itm80ea670ef0bfc",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/infinix-smart-10-titanium-silver-64-gb/p/itm0bde9cee1963a"
  },
  "moto-60-fusion": {
    "brand": "Motorola",
    "name": "Motorola 60 Fusion",
    "colorNames": [
      "Eclipse Black",
      "Marshmallow Blue"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 21849,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-fusion-5g-pantone-slipstream-128-gb/p/itm3ddb7e06211f1",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 24999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-fusion-5g-pantone-amazonite-256-gb/p/itm9218b12ff853f",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-fusion-5g-pantone-slipstream-128-gb/p/itm3ddb7e06211f1"
  },
  "moto-70-fusion": {
    "brand": "Motorola",
    "name": "Motorola 70 Fusion",
    "colorNames": [
      "Koala Grey",
      "Ballad Blue"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 30399,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion-pantone-blue-surf-256-gb/p/itm8617d6ad959da",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 29499,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion-pantone-blue-surf-512-gb/p/itm87b81fff91d44",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 29499,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion-pantone-blue-surf-256-gb/p/itm6383107cab140",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 31999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion-pantone-blue-surf-512-gb/p/itm87b81fff91d44",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion-pantone-blue-surf-256-gb/p/itm8617d6ad959da"
  },
  "moto-edge-60": {
    "brand": "Motorola",
    "name": "Motorola Edge 60",
    "colorNames": [
      "Koala Grey",
      "Ballad Blue",
      "Pantone Nautical Blue"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 27999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-dazzling-blue-256-gb/p/itmbe844b03e063b",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 36099,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-512-gb/p/itm106024b11b487",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 27999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-5g-pantone-gibraltar-sea-256-gb/p/itmc7ab8f1263d42",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 36099,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-dazzling-blue-512-gb/p/itmdc36ec357d827",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-dazzling-blue-256-gb/p/itmbe844b03e063b"
  },
  "moto-edge-60-pro": {
    "brand": "Motorola",
    "name": "Motorola Edge 60 Pro",
    "colorNames": [
      "Pantone Nautical Blue",
      "Pantone Gibraltar Sea"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-dazzling-blue-256-gb/p/itmbe844b03e063b",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 36099,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-512-gb/p/itm106024b11b487",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 32299,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-walnut-256-gb/p/itm77d7138c41207",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 36099,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-512-gb/p/itm106024b11b487",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-dazzling-blue-256-gb/p/itmbe844b03e063b"
  },
  "moto-edge-70-pro": {
    "brand": "Motorola",
    "name": "Motorola Edge 70 Pro",
    "colorNames": [
      "Pantone Lily White",
      "Pantone Titan",
      "Pantone Tea",
      "Pantone Zinfandel",
      "Pantone Chicory Coffee"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 37999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-pro-pantone-tea-256-gb/p/itm8e1524c8da543",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 31999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion/p/itm0119095a14fb0",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 37999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-pro-pantone-zinfandel-256-gb/p/itm70caeee0ca941",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 37999,
        "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-pro-pantone-tea-256-gb/p/itm8e1524c8da543",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-pro-pantone-tea-256-gb/p/itm8e1524c8da543"
  },
  "moto-g06-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G06 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 13299,
        "flipkartUrl": "https://www.flipkart.com/motorola-g06-power-pantone-tendril-64-gb/p/itm2f1ca967879c9",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 12999,
        "flipkartUrl": "https://www.flipkart.com/arya-design-gallery-back-cover-motorola-moto-g06-power-4g/p/itmaddc0a43b3c35",
        "verified": false
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 13299,
        "flipkartUrl": "https://www.flipkart.com/motorola-g06-power-pantone-tapestry-64-gb/p/itm29390fa68401d",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 12999,
        "flipkartUrl": "https://www.flipkart.com/arya-design-gallery-back-cover-motorola-moto-g06-power-4g/p/itmaddc0a43b3c35",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-g06-power-pantone-tendril-64-gb/p/itm2f1ca967879c9"
  },
  "moto-g37": {
    "brand": "Motorola",
    "name": "Motorola Moto G37",
    "colorNames": [
      "Ocean Blue",
      "Charcoal Black"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 13299,
        "flipkartUrl": "https://www.flipkart.com/motorola-g37-pantone-nautical-blue-64-gb/p/itm5d235b295291f",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 15199,
        "flipkartUrl": "https://www.flipkart.com/motorola-g37-power-pantone-nautical-blue-128-gb/p/itmf752f4981d932",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 13299,
        "flipkartUrl": "https://www.flipkart.com/motorala-g37-pantone-nautical-blue-64-gb/p/itm2afe0a88dbd9f",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 15199,
        "flipkartUrl": "https://www.flipkart.com/motorola-g37-power-pantone-nautical-blue-128-gb/p/itmf752f4981d932",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-g37-pantone-nautical-blue-64-gb/p/itm5d235b295291f"
  },
  "moto-g37-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G37 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 18999,
        "flipkartUrl": "https://www.flipkart.com/motorola-g37-power-pantone-capri-128-gb/p/itm5dc5774d4d5e9",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 14999,
        "flipkartUrl": "https://www.flipkart.com/gdbuy-back-cover-realme-13-5g-5g/p/itm7923842486e34",
        "verified": false
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 15199,
        "flipkartUrl": "https://www.flipkart.com/motorola-g37-power-pantone-nautical-blue-128-gb/p/itmf752f4981d932",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 14999,
        "flipkartUrl": "https://www.flipkart.com/gdbuy-back-cover-realme-13-5g-5g/p/itm7923842486e34",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-g37-power-pantone-capri-128-gb/p/itm5dc5774d4d5e9"
  },
  "moto-g57-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G57 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 19949,
        "flipkartUrl": "https://www.flipkart.com/motorola-g57-power-5g-snapdragon-pantone-corsair-128-gb/p/itm8332e9aa80c32",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 18999,
        "flipkartUrl": "https://www.flipkart.com/smartcase-back-cover-moto-g57-power-5g-motorola-5g/p/itm2f3c2b594fe12",
        "verified": false
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 19949,
        "flipkartUrl": "https://www.flipkart.com/motorola-g57-power-5g-snapdragon-pantone-corsair-128-gb/p/itm8332e9aa80c32",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 18999,
        "flipkartUrl": "https://www.flipkart.com/smartcase-back-cover-moto-g57-power-5g-motorola-5g/p/itm2f3c2b594fe12",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-g57-power-5g-snapdragon-pantone-corsair-128-gb/p/itm8332e9aa80c32"
  },
  "moto-g96": {
    "brand": "Motorola",
    "name": "Motorola Moto G96",
    "colorNames": [
      "Sage Green",
      "Meteor Grey",
      "Ballad Blue"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 21849,
        "flipkartUrl": "https://www.flipkart.com/motorola-g96-5g-pantone-ashleigh-blue-256-gb/p/itmda6d829eead4b",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/vmt-stock-back-cover-motorola-moto-g96-5g/p/itmb07c5a9c783cc",
        "verified": false
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 21849,
        "flipkartUrl": "https://www.flipkart.com/motorola-g96-5g-pantone-ashleigh-blue-256-gb/p/itmda6d829eead4b",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/vmt-stock-back-cover-motorola-moto-g96-5g/p/itmb07c5a9c783cc",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/motorola-g96-5g-pantone-ashleigh-blue-256-gb/p/itmda6d829eead4b"
  },
  "narzo-80-lite": {
    "brand": "Narzo",
    "name": "Realme Narzo 80 Lite",
    "colorNames": [
      "Beach Gold",
      "Obsidian Black",
      "Crystal Purple"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 10999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-80-lite-beach-gold-64-gb/p/itmda40eecbc001f",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 10999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-80-lite-5g-onyx-black-128-gb/p/itm47ab7fdec3924",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 10999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-80-lite-beach-gold-64-gb/p/itmda40eecbc001f",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 10999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-80-lite-4g-obsidian-black-128-gb/p/itm2890cac28063f",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-narzo-80-lite-beach-gold-64-gb/p/itmda40eecbc001f"
  },
  "narzo-90": {
    "brand": "Narzo",
    "name": "Realme Narzo 90",
    "colorNames": [
      "Victory Gold",
      "Carbon Black"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 15999,
        "flipkartUrl": "https://www.flipkart.com/realme-90x-5g-flash-blue-128-gb/p/itm6d58bc292ef4d",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 15999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-90-5g-victory-gold-128-gb/p/itm6464e1056a2e4",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-90x-5g-flash-blue-128-gb/p/itm6d58bc292ef4d"
  },
  "narzo-90x": {
    "brand": "Narzo",
    "name": "Realme Narzo 90x",
    "colorNames": [
      "Flash Blue",
      "Nitro Blue"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 17999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-90x-5g-flash-blue-128-gb/p/itma63c5c5ce781a",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 17999,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-90x-5g-flash-blue-128-gb/p/itma63c5c5ce781a",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-narzo-90x-5g-flash-blue-128-gb/p/itma63c5c5ce781a"
  },
  "narzo-n53": {
    "brand": "Narzo",
    "name": "Realme Narzo N53",
    "colorNames": [
      "Feather Gold",
      "Feather Black"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 9887,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-n53-feather-black-64-gb/p/itm3061a0a591574",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 9887,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-n53-feather-black-128-gb/p/itm3061a0a591574",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 9887,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-n61-marble-black-64-gb/p/itm4a7b7f6160ff8",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 9887,
        "flipkartUrl": "https://www.flipkart.com/realme-narzo-n53-feather-black-128-gb/p/itm3061a0a591574",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-narzo-n53-feather-black-64-gb/p/itm3061a0a591574"
  },
  "oneplus-z2-anc": {
    "brand": "OnePlus",
    "name": "OnePlus Buds Z2 ANC",
    "colorNames": [
      "Black",
      "White"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 999,
        "verified": false
      }
    ]
  },
  "oneplus-z3": {
    "brand": "OnePlus",
    "name": "OnePlus Buds Z3",
    "colorNames": [
      "Black",
      "White",
      "Blue"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 1499,
        "amazonUrl": "https://www.amazon.in/AirDapp-Silicone-Protective-OnePlus-Earphone/dp/B0B6T5DB2X",
        "verified": true
      }
    ],
    "amazonUrl": "https://www.amazon.in/AirDapp-Silicone-Protective-OnePlus-Earphone/dp/B0B6T5DB2X"
  },
  "oneplus-nord-ce6": {
    "brand": "OnePlus",
    "name": "OnePlus Nord CE6",
    "colorNames": [
      "Dark Chrome",
      "Cloud Trinity"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 33985,
        "amazonUrl": "https://www.amazon.in/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLHVJRH",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 33985,
        "amazonUrl": "https://www.amazon.in/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLDWKF3",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 33985,
        "amazonUrl": "https://www.amazon.in/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLHVJRH",
        "verified": false
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 33985,
        "amazonUrl": "https://www.amazon.in/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLHVJRH",
        "verified": false
      }
    ],
    "amazonUrl": "https://www.amazon.in/OnePlus-Snapdragon-Segments-Fastest-Response/dp/B0GWLHVJRH"
  },
  "oneplus-nord-ce6-lite": {
    "brand": "OnePlus",
    "name": "OnePlus Nord CE6 Lite",
    "colorNames": [
      "Pastel Lime",
      "Aqua Surge"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 29499,
        "amazonUrl": "https://www.amazon.in/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYDLJJQ",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 29499,
        "amazonUrl": "https://www.amazon.in/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYF57G9",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 29499,
        "amazonUrl": "https://www.amazon.in/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYDLJJQ",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 29499,
        "amazonUrl": "https://www.amazon.in/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYF57G9",
        "verified": true
      }
    ],
    "amazonUrl": "https://www.amazon.in/OnePlus-Segments-Dimensity-Processor-Recording/dp/B0GVYDLJJQ"
  },
  "oppo-k13": {
    "brand": "Oppo",
    "name": "Oppo K13",
    "colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/oppo-k13-turbo-5g-white-knight-128-gb/p/itm3692362cd3df3",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/oppo-k13-turbo-pro-5g-silver-knight-256-gb/p/itmeefeb718f01fe",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/oppo-k13-turbo-5g-white-knight-128-gb/p/itm3692362cd3df3",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/oppo-k13-turbo-pro-5g-silver-knight-256-gb/p/itmeefeb718f01fe",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/oppo-k13-turbo-5g-white-knight-128-gb/p/itm3692362cd3df3"
  },
  "oppo-k13x": {
    "brand": "Oppo",
    "name": "Oppo K13x",
    "colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k13x-5g-6000mah-45w-supervooc-charger-ai-midnight-violet-128-gb/p/itm62b2e62fbb43e",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 15199,
        "flipkartUrl": "https://www.flipkart.com/oppo-playzone/p/itm71373f05250b0",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k13x-5g-6000mah-45w-supervooc-charger-ai-midnight-violet-128-gb/p/itm62b2e62fbb43e",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 15199,
        "flipkartUrl": "https://www.flipkart.com/oppo-playzone/p/itm71373f05250b0",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/oppo-k13x-5g-6000mah-45w-supervooc-charger-ai-midnight-violet-128-gb/p/itm62b2e62fbb43e"
  },
  "oppo-k14": {
    "brand": "Oppo",
    "name": "Oppo K14",
    "colorNames": [
      "Iron Grey",
      "Ice Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-128-gb/p/itm2a5cc1d23c2af",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-256-gb/p/itm2a5cc1d23c2af",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-128-gb/p/itm2a5cc1d23c2af",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 41480,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno14-5g/p/itm4d9e853eee6cf",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-128-gb/p/itm2a5cc1d23c2af"
  },
  "oppo-k14x": {
    "brand": "Oppo",
    "name": "Oppo K14x",
    "colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 17999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14x-5g-prism-violet-128-gb/p/itmdcac5ae642971",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-256-gb/p/itm2a5cc1d23c2af",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 17999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14x-5g-prism-violet-128-gb/p/itmdcac5ae642971",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-256-gb/p/itm2a5cc1d23c2af",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/oppo-k14x-5g-prism-violet-128-gb/p/itmdcac5ae642971"
  },
  "oppo-reno-15": {
    "brand": "Oppo",
    "name": "Oppo Reno 15",
    "colorNames": [
      "Silver Moon",
      "Midnight Black",
      "Aurora Green"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 39999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-256-gb/p/itm37cc91d1c2807",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 39999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-512-gb/p/itm37cc91d1c2807",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 39999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-256-gb/p/itm37cc91d1c2807",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 39999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-512-gb/p/itm37cc91d1c2807",
        "verified": true
      },
      {
        "ram": "16 GB",
        "storage": "256 GB",
        "price": 39999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-256-gb/p/itm37cc91d1c2807",
        "verified": true
      },
      {
        "ram": "16 GB",
        "storage": "512 GB",
        "price": 39999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-512-gb/p/itm37cc91d1c2807",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-256-gb/p/itm37cc91d1c2807"
  },
  "oppo-reno-15c": {
    "brand": "Oppo",
    "name": "Oppo Reno 15C",
    "colorNames": [
      "Starlight White",
      "Midnight Black"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 20999,
        "flipkartUrl": "https://www.flipkart.com/redmi-15c-5g-moonlight-blue-128-gb/p/itmc1345bb45eef3",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 31349,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15c-5g-twilight-blue-256-gb/p/itmc54a5df4d2236",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 36999,
        "flipkartUrl": "https://www.flipkart.com/7printzone-back-cover-oppo-reno-15c-5g/p/itme96cc35f14277",
        "verified": false
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 36999,
        "flipkartUrl": "https://www.flipkart.com/oppo-reno15c-5g-twilight-blue-256-gb/p/itmc54a5df4d2236",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/redmi-15c-5g-moonlight-blue-128-gb/p/itmc1345bb45eef3"
  },
  "poco-c71": {
    "brand": "POCO",
    "name": "POCO C71",
    "colorNames": [
      "Power Black",
      "Coral Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 6999,
        "flipkartUrl": "https://www.flipkart.com/poco-c71-desert-gold-64-gb/p/itme3dc58af6a04b",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 6999,
        "flipkartUrl": "https://www.flipkart.com/poco-c71-power-black-128-gb/p/itm8096ee52d7013",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 6999,
        "flipkartUrl": "https://www.flipkart.com/poco-c71-desert-gold-64-gb/p/itme3dc58af6a04b",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 6999,
        "flipkartUrl": "https://www.flipkart.com/poco-c71-power-black-128-gb/p/itm8096ee52d7013",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/poco-c71-desert-gold-64-gb/p/itme3dc58af6a04b"
  },
  "poco-c85": {
    "brand": "POCO",
    "name": "POCO C85",
    "colorNames": [
      "Power Black",
      "Coral Green"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85-5g-charger-box-power-black-128-gb/p/itm00a5a3f301b9c",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85-5g-mystic-purple-128-gb/p/itm74e2143a5de24",
        "verified": false
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85-5g-mystic-purple-128-gb/p/itm74e2143a5de24",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 13999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85-5g-mystic-purple-128-gb/p/itm74e2143a5de24",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/poco-c85-5g-charger-box-power-black-128-gb/p/itm00a5a3f301b9c"
  },
  "poco-c85x": {
    "brand": "POCO",
    "name": "POCO C85x",
    "colorNames": [
      "Power Black",
      "Coral Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 11999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85x-green-64-gb/p/itm96bce2b7909b7",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 11999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85x-black-128-gb/p/itm7e422d0bdc317",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 11999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85x-green-64-gb/p/itm96bce2b7909b7",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 11999,
        "flipkartUrl": "https://www.flipkart.com/poco-c85x-black-128-gb/p/itm7e422d0bdc317",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/poco-c85x-green-64-gb/p/itm96bce2b7909b7"
  },
  "poco-m7": {
    "brand": "POCO",
    "name": "POCO M7",
    "colorNames": [
      "Graphite Black",
      "Aurora Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 12349,
        "flipkartUrl": "https://www.flipkart.com/poco-m7-pro-5g-lunar-dust-128-gb/p/itm59a079d57519a",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 16149,
        "flipkartUrl": "https://www.flipkart.com/poco-m7-pro-5g-lunar-dust-256-gb/p/itmf2e9e7e09f237",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 12349,
        "flipkartUrl": "https://www.flipkart.com/poco-m7-pro-5g-lunar-dust-128-gb/p/itm59a079d57519a",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 12999,
        "flipkartUrl": "https://www.flipkart.com/poco-m7-pro-5g-lunar-dust-256-gb/p/itmf2e9e7e09f237",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/poco-m7-pro-5g-lunar-dust-128-gb/p/itm59a079d57519a"
  },
  "realme-15": {
    "brand": "Realme",
    "name": "Realme 15",
    "colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 24999,
        "flipkartUrl": "https://www.flipkart.com/realme-15-5g-flowing-silver-128-gb/p/itme9581fbd0e97a",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 24999,
        "flipkartUrl": "https://www.flipkart.com/realme-15-pro-5g-flowing-silver-256-gb/p/itm216cdbf4baea0",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 24999,
        "flipkartUrl": "https://www.flipkart.com/realme-15-5g-flowing-silver-128-gb/p/itme9581fbd0e97a",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 24999,
        "flipkartUrl": "https://www.flipkart.com/realme-15-pro-5g-flowing-silver-256-gb/p/itm216cdbf4baea0",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-15-5g-flowing-silver-128-gb/p/itme9581fbd0e97a"
  },
  "realme-15t": {
    "brand": "Realme",
    "name": "Realme 15T",
    "colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/realme-15t-5g-flowing-silver-128-gb/p/itm3f28d98da183c",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/product/p/itme",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/realme-15t-5g-flowing-silver-128-gb/p/itm3f28d98da183c",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/realme-15t-5g-flowing-silver-128-gb/p/itm3f28d98da183c",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-15t-5g-flowing-silver-128-gb/p/itm3f28d98da183c"
  },
  "realme-15x": {
    "brand": "Realme",
    "name": "Realme 15x",
    "colorNames": [
      "Speed Green",
      "Racing Black",
      "Champion Gold"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 24699,
        "flipkartUrl": "https://www.flipkart.com/realme-15x-5g-aqua-blue-128-gb/p/itmcf22f2a57724f",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 23999,
        "flipkartUrl": "https://www.flipkart.com/realme-15x-aqua-blue-128-gb/p/itmd7ef70dbda3a0",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 24699,
        "flipkartUrl": "https://www.flipkart.com/realme-15x-5g-aqua-blue-128-gb/p/itmcf22f2a57724f",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 23999,
        "flipkartUrl": "https://www.flipkart.com/realme-15x-aqua-blue-128-gb/p/itmd7ef70dbda3a0",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-15x-5g-aqua-blue-128-gb/p/itmcf22f2a57724f"
  },
  "realme-c71": {
    "brand": "Realme",
    "name": "Realme C71",
    "colorNames": [
      "Meadow Green",
      "Twilight Purple"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/realme-c71-dune-gold-64-gb/p/itm81ab68c80d75d",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/realme-c71-sea-blue-128-gb/p/itm920c5c8761871",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/realme-c71-dune-gold-64-gb/p/itm81ab68c80d75d",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/realme-c71-sea-blue-128-gb/p/itm920c5c8761871",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-c71-dune-gold-64-gb/p/itm81ab68c80d75d"
  },
  "realme-p4-lite": {
    "brand": "Realme",
    "name": "Realme P4 Lite",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 11399,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-lite-5g-mosaic-blue-64-gb/p/itm90c243961f214",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 15999,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-lite-sea-blue-128-gb/p/itm029fbc88fdc91",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 11399,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-lite-5g-mosaic-blue-64-gb/p/itm90c243961f214",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 15561,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-5g-iwit-steel-grey-128-gb/p/itme87f580f5b4fd",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-p4-lite-5g-mosaic-blue-64-gb/p/itm90c243961f214"
  },
  "realme-p4-power": {
    "brand": "Realme",
    "name": "Realme P4 Power",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 28499,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-power-5g-transsilver-128-gb/p/itm49784b322aad0",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-power-5g-transsilver-128-gb/p/itm49784b322aad0",
        "verified": false
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 30999,
        "flipkartUrl": "https://www.flipkart.com/product/p/itme",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 25999,
        "flipkartUrl": "https://www.flipkart.com/realme-p4-power-5g-transsilver-128-gb/p/itm49784b322aad0",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-p4-power-5g-transsilver-128-gb/p/itm49784b322aad0"
  },
  "realme-p4x": {
    "brand": "Realme",
    "name": "Realme P4x",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 19499,
        "flipkartUrl": "https://www.flipkart.com/realme-p4x-5g-lake-green-128-gb/p/itm575b1540859e4",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 19499,
        "flipkartUrl": "https://www.flipkart.com/realme-p4x-5g-lake-green-128-gb/p/itm575b1540859e4",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 19499,
        "flipkartUrl": "https://www.flipkart.com/realme-p4x-5g-lake-green-128-gb/p/itm575b1540859e4",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 19499,
        "flipkartUrl": "https://www.flipkart.com/realme-p4x-5g-lake-green-128-gb/p/itm575b1540859e4",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/realme-p4x-5g-lake-green-128-gb/p/itm575b1540859e4"
  },
  "redmi-a4": {
    "brand": "Redmi",
    "name": "Redmi A4",
    "colorNames": [
      "Midnight Black",
      "Starlight Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 12999,
        "amazonUrl": "https://www.amazon.in/Redmi-A4-5G-Sparkle-Charging/dp/B0DLW427YG",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 12999,
        "amazonUrl": "https://www.amazon.in/Redmi-Sparkle-Storage-Segment-Charging/dp/B0DLW44CGS",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 12999,
        "amazonUrl": "https://www.amazon.in/Redmi-A4-5G-Storage-Charging/dp/B0FBRM15FH",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 12999,
        "amazonUrl": "https://www.amazon.in/Redmi-A4-5G-Storage-Charging/dp/B0FBRM15FH",
        "verified": true
      }
    ],
    "amazonUrl": "https://www.amazon.in/Redmi-A4-5G-Sparkle-Charging/dp/B0DLW427YG"
  },
  "samsung-m06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M06",
    "colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4 GB",
        "storage": "64 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-m06-5g-blazing-black-64-gb/p/itm0c7e356cd6ad6",
        "verified": true
      },
      {
        "ram": "4 GB",
        "storage": "128 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/samsung-m06-5g-blazing-black-128-gb/p/itmcafa42dadc15c",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "64 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-m06-5g-blazing-black-64-gb/p/itm0c7e356cd6ad6",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 11499,
        "flipkartUrl": "https://www.flipkart.com/samsung-m06-5g-blazing-black-128-gb/p/itmcafa42dadc15c",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-m06-5g-blazing-black-64-gb/p/itm0c7e356cd6ad6"
  },
  "samsung-m36": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M36",
    "colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/samsung-m36-5g-light-green-128-gb/p/itm4cf1eae54334f",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/samsung-m36-5g-black-256-gb/p/itm74130a5a313b6",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/samsung-m36-5g-light-green-128-gb/p/itm4cf1eae54334f",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 17499,
        "flipkartUrl": "https://www.flipkart.com/samsung-m36-5g-black-256-gb/p/itm74130a5a313b6",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/samsung-m36-5g-light-green-128-gb/p/itm4cf1eae54334f"
  },
  "samsung-s25-fe": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S25 FE",
    "colorNames": [
      "Icyblue",
      "Jetblack",
      "Navy",
      "White"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 64999,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-fe-5g-navy-128-gb/p/itm7c78f4eee8160",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 65999,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-fe-5g-white-256-gb/p/itm686ea83612e85",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "512 GB",
        "price": 64999,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-fe-5g-white-128-gb/p/itm686ea83612e85",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-fe-5g-navy-128-gb/p/itm7c78f4eee8160"
  },
  "samsung-s25-ultra": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S25 Ultra",
    "colorNames": [
      "Titanium Silverblue",
      "Titanium Black",
      "Titanium Gray",
      "Titanium Whitesilver"
    ],
    "variants": [
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 84739,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-silverblue-256-gb/p/itm413a5c3f30151",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 125990,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-black-512-gb/p/itmc5f14b041aa5b",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "1 TB",
        "price": 88739,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-silverblue-1024-gb/p/itm7d0e1ef71672e",
        "verified": false
      },
      {
        "ram": "16 GB",
        "storage": "256 GB",
        "price": 84739,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-silverblue-256-gb/p/itm413a5c3f30151",
        "verified": true
      },
      {
        "ram": "16 GB",
        "storage": "512 GB",
        "price": 125990,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-black-512-gb/p/itmc5f14b041aa5b",
        "verified": true
      },
      {
        "ram": "16 GB",
        "storage": "1 TB",
        "price": 88739,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-silverblue-1024-gb/p/itm7d0e1ef71672e",
        "verified": false
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-silverblue-256-gb/p/itm413a5c3f30151"
  },
  "samsung-s26-plus": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S26+",
    "colorNames": [
      "Black",
      "Cobalt Violet",
      "Sky Blue",
      "White",
      "Pink Gold",
      "Silver Shadow"
    ],
    "variants": [
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 114999,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s26-5g-black-256-gb/p/itmf5ed5d08eef13",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "512 GB",
        "price": 114999,
        "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s26-5g-black-512-gb/p/itmf5ed5d08eef13",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s26-5g-black-256-gb/p/itmf5ed5d08eef13"
  },
  "vivo-t4-lite": {
    "brand": "Vivo",
    "name": "Vivo T4 Lite",
    "colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-lite-5g-2026-titanium-gold-128-gb/p/itm08f41580b36a4",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-lite-5g-prism-blue-2026-8gb-256gb/p/itm49fb53d099f3c",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-lite-5g-2026-titanium-gold-128-gb/p/itm08f41580b36a4",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 19999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-lite-5g-prism-blue-2026-8gb-256gb/p/itm49fb53d099f3c",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/vivo-t4-lite-5g-2026-titanium-gold-128-gb/p/itm08f41580b36a4"
  },
  "vivo-t4-pro": {
    "brand": "Vivo",
    "name": "Vivo T4 Pro",
    "colorNames": [
      "Nitro Blue",
      "Blaze Gold"
    ],
    "variants": [
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 27999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-pro-5g-nitro-blue-128-gb/p/itm4da1824b696d9",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 27999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-pro-5g-blaze-gold-256-gb/p/itm4da1824b696d9",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "128 GB",
        "price": 27999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-pro-5g-nitro-blue-128-gb/p/itm4da1824b696d9",
        "verified": true
      },
      {
        "ram": "12 GB",
        "storage": "256 GB",
        "price": 27999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4-pro-5g-blaze-gold-256-gb/p/itm4da1824b696d9",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/vivo-t4-pro-5g-nitro-blue-128-gb/p/itm4da1824b696d9"
  },
  "vivo-t4r": {
    "brand": "Vivo",
    "name": "Vivo T4R",
    "colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6 GB",
        "storage": "128 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4r-5g-twilight-blue-128-gb/p/itm3a5653667cb9c",
        "verified": true
      },
      {
        "ram": "6 GB",
        "storage": "256 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4r-5g-twilight-blue-128-gb/p/itm3a5653667cb9c",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "128 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4r-5g-twilight-blue-128-gb/p/itm3a5653667cb9c",
        "verified": true
      },
      {
        "ram": "8 GB",
        "storage": "256 GB",
        "price": 21999,
        "flipkartUrl": "https://www.flipkart.com/vivo-t4r-5g-twilight-blue-128-gb/p/itm3a5653667cb9c",
        "verified": true
      }
    ],
    "flipkartUrl": "https://www.flipkart.com/vivo-t4r-5g-twilight-blue-128-gb/p/itm3a5653667cb9c"
  }
};

export const DIRECT_URLS_META = {
  "generatedAt": "2026-07-13T08:33:39.446Z",
  "source": "C:\\Users\\ramak\\Downloads\\products_with_direct_urls.csv",
  "matched": 56,
  "unknown": [],
  "searchUrls": [],
  "totalVariants": 198
};
