// AUTO-GENERATED by scripts/build-direct-urls-data.ts from C:\Users\ramak\Downloads\products_with_direct_urls.csv
// Do not edit by hand. Re-run `npm run direct-urls:build` to regenerate.
import type { DirectUrlProduct } from "./direct-urls-parse";

export const DIRECT_URLS_BY_SLUG: Record<string, DirectUrlProduct> = {
  "airpods-4": {
    "brand": "Apple",
    "name": "Apple AirPods 4",
    
    "amazonUrl": "https://www.amazon.in/Apple-Bluetooth-Headphones-Personalised-Effortless/dp/B0DGJLL7V1",
    "flipkartUrl": "https://www.flipkart.com/apple-airpods-4-wireless-earbuds-personalised-spatial-audio-sweat-water-resistant-bluetooth/p/itmdf102348be4b9",
    "colorNames": [
      "White (Standard)"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 17900,
        "verified": true
      }
    ]
  },
  "iphone-17": {
    "brand": "Apple",
    "name": "iPhone 17",
    "colorNames": [
      "Lavender",
      "Sage",
      "Mist Blue",
      "White",
      "Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 82900,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "512GB",
        "price": 92900,
        "verified": true
      }
    ]
  },
  "iphone-17-air": {
    "brand": "Apple",
    "name": "iPhone 17 Air",
    "colorNames": [
      "Sky Blue",
      "Light Gold",
      "Cloud White",
      "Space Black"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 99900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 109900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "1TB",
        "price": 129900,
        "verified": true
      }
    ]
  },
  "iphone-17-pro": {
    "brand": "Apple",
    "name": "iPhone 17 Pro",
    "colorNames": [
      "Cosmic Orange",
      "Deep Blue",
      "Silver"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 132900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 142900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "1TB",
        "price": 162900,
        "verified": true
      }
    ]
  },
  "iphone-17-pro-max": {
    "brand": "Apple",
    "name": "iPhone 17 Pro Max",
    "colorNames": [
      "Silver",
      "Cosmic Orange",
      "Deep Blue"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 101900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 111900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "1TB",
        "price": 131900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "2TB",
        "price": 151900,
        "verified": true
      }
    ]
  },
  "pixel-10": {
    "brand": "Google",
    "name": "Google Pixel 10",
    
    "flipkartUrl": "https://www.flipkart.com/google-pixel-10-frost-256-gb/p/itm180af25bcc197",
    "colorNames": [
      "Indigo",
      "Frost",
      "Lemongrass",
      "Obsidian"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "128GB",
        "price": 74999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 84999,
        "verified": true
      }
    ]
  },
  "pixel-10a": {
    "brand": "Google",
    "name": "Google Pixel 10a",
    "flipkartUrl": "https://www.flipkart.com/google-pixel-10a-lavender-256-gb/p/itmba3073a0f391e",
"colorNames": [
      "Obsidian",
      "Porcelain",
      "Aloe",
      "Bay"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 49999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 59999,
        "verified": true
      }
    ]
  },
  "hmd-vibe-2": {
    "brand": "HMD",
    "name": "HMD Vibe 2",
    "colorNames": [
      "Cosmic Lavender",
      "Nordic Blue",
      "Peach Pink"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      }
    ]
  },
  "infinix-gt-30": {
    "brand": "Infinix",
    "name": "Infinix GT 30",
    "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-5g-cyber-blue-128-cyber-blue-gb/p/itmcda81613113c6",
"colorNames": [
      "Pulse Green",
      "Cyber Blue",
      "Blade White"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20999,
        "verified": true
      }
    ]
  },
  "infinix-gt-30-pro": {
    "brand": "Infinix",
    "name": "Infinix GT 30 Pro",
    "flipkartUrl": "https://www.flipkart.com/infinix-gt-30-pro-5g-dark-flare-256-gb/p/itmd4bc1852572b9",
"colorNames": [
      "Dark Flare",
      "Blade White",
      "Shadow Ash"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 26999,
        "verified": true
      }
    ]
  },
  "infinix-note-edge": {
    "brand": "Infinix",
    "name": "Infinix Note Edge",
    "colorNames": [
      "Shadow Black",
      "Solar Orange",
      "Lunar Titanium",
      "Silk Green",
      "Stellar Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 16999,
        "verified": true
      }
    ]
  },
  "infinix-smart-10": {
    "brand": "Infinix",
    "name": "Infinix Smart 10",
    "flipkartUrl": "https://www.flipkart.com/infinix-smart-10-titanium-silver-64-gb/p/itm0bde9cee1963a",
"colorNames": [
      "Black",
      "Blue",
      "Green"
    ],
    "variants": [
      {
        "ram": "3GB",
        "storage": "64GB",
        "price": 6499,
        "verified": true
      },
      {
        "ram": "4GB",
        "storage": "128GB",
        "price": 7499,
        "verified": true
      }
    ]
  },
  "infinix-smart-20": {
    "brand": "Infinix",
    "name": "Infinix Smart 20",
"colorNames": [
      "Sunlit Orange",
      "Black",
      "Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 6999,
        "verified": true
      },
      {
        "ram": "4GB",
        "storage": "128GB",
        "price": 7999,
        "verified": true
      }
    ]
  },
  "moto-60-fusion": {
    "brand": "Motorola",
    "name": "Motorola 60 Fusion",
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-fusion-5g-pantone-zephyr-256-gb/p/itmc9dbbd784b6bc",
"colorNames": [
      "Eclipse Black",
      "Marshmallow Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      }
    ]
  },
  "moto-70-fusion": {
    "brand": "Motorola",
    "name": "Motorola 70 Fusion",
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-fusion-pantone-country-air-128-gb/p/itmbae68fc092d22",
"colorNames": [
      "Koala Grey",
      "Ballad Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 33999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 38999,
        "verified": true
      }
    ]
  },
  "moto-edge-60": {
    "brand": "Motorola",
    "name": "Motorola Edge 60",
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-5g/p/itm18a81b952d716",
"colorNames": [
      "Koala Grey",
      "Ballad Blue",
      "Pantone Nautical Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "moto-edge-60-pro": {
    "brand": "Motorola",
    "name": "Motorola Edge 60 Pro",
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-60-pro-pantone-shadow-256-gb/p/itme4f8c6dd0e2db",
"colorNames": [
      "Pantone Nautical Blue",
      "Pantone Gibraltar Sea"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "moto-edge-70-pro": {
    "brand": "Motorola",
    "name": "Motorola Edge 70 Pro",
    "flipkartUrl": "https://www.flipkart.com/motorola-edge-70-pro-pantone-tea-256-gb/p/itm8e1524c8da543",
"colorNames": [
      "Pantone Lily White",
      "Pantone Titan",
      "Pantone Tea",
      "Pantone Zinfandel",
      "Pantone Chicory Coffee"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 44999,
        "verified": true
      }
    ]
  },
  "moto-g06-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G06 Power",
    "flipkartUrl": "https://www.flipkart.com/motorola-g06-power-pantone-tapestry-64-gb/p/itm29390fa68401d",
"colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      }
    ]
  },
  "moto-g37": {
    "brand": "Motorola",
    "name": "Motorola Moto G37",
    "colorNames": [
      "Ocean Blue",
      "Charcoal Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 10000,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11999,
        "verified": true
      }
    ]
  },
  "moto-g37-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G37 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "moto-g57-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G57 Power",
    "flipkartUrl": "https://www.flipkart.com/motorola-g57-power-5g-snapdragon-pantone-regatta-128-gb/p/itmdab5f9f1bf87b",
"colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 20999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 23999,
        "verified": true
      }
    ]
  },
  "moto-g67-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G67 Power",
    "flipkartUrl": "https://www.flipkart.com/motorola-g67-power-5g-snapdragon-pantone-cilantro-128-gb/p/itmb96be3c1b56cd",
"colorNames": [
      "Ocean Blue",
      "Charcoal Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 10000,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11999,
        "verified": true
      }
    ]
  },
  "moto-g96": {
    "brand": "Motorola",
    "name": "Motorola Moto G96",
    "colorNames": [
      "Sage Green",
      "Meteor Grey",
      "Ballad Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 24999,
        "verified": true
      }
    ]
  },
  "narzo-100-lite": {
    "brand": "Narzo",
    "name": "Realme Narzo 100 Lite",
    "colorNames": [
      "Frost Silver",
      "Thunder Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 18320,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 20320,
        "verified": true
      }
    ]
  },
  "narzo-80-lite": {
    "brand": "Narzo",
    "name": "Realme Narzo 80 Lite",
    "colorNames": [
      "Beach Gold",
      "Obsidian Black",
      "Crystal Purple"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      }
    ]
  },
  "narzo-90": {
    "brand": "Narzo",
    "name": "Realme Narzo 90",
    "colorNames": [
      "Victory Gold",
      "Carbon Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "narzo-90x": {
    "brand": "Narzo",
    "name": "Realme Narzo 90x",
    "colorNames": [
      "Flash Blue",
      "Nitro Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 19998,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 21998,
        "verified": true
      }
    ]
  },
  "narzo-n53": {
    "brand": "Narzo",
    "name": "Realme Narzo N53",
    "colorNames": [
      "Feather Gold",
      "Feather Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 9887,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11887,
        "verified": true
      }
    ]
  },
  "narzo-power": {
    "brand": "Narzo",
    "name": "Realme Narzo Power",
    "colorNames": [
      "Titan Silver",
      "Titan Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 37998,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 41998,
        "verified": true
      }
    ]
  },
  "oneplus-13": {
    "brand": "OnePlus",
    "name": "OnePlus 13",
    "amazonUrl": "https://www.amazon.in/OnePlus-13-256GB-Midnight-Ocean/dp/B0DPS7FB4J",
    "flipkartUrl": "https://www.flipkart.com/oneplus-13-black-eclipse-256-gb/p/itmb4659fd2a037f",
"colorNames": [
      "Midnight Ocean",
      "Arctic Dawn",
      "Black Eclipse"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 57999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 67999,
        "verified": true
      },
      {
        "ram": "24GB",
        "storage": "1TB",
        "price": 82999,
        "verified": true
      }
    ]
  },
  "oneplus-z2-anc": {
    "brand": "OnePlus",
    "name": "OnePlus Buds Z2 ANC",
    
    "flipkartUrl": "https://www.flipkart.com/oneplus-buds-z2-active-noise-cancellation-bluetooth/p/itm88b7c4b3f5397",
    "colorNames": [
      "Black",
      "White"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 999,
        "verified": true
      }
    ]
  },
  "oneplus-z3": {
    "brand": "OnePlus",
    "name": "OnePlus Buds Z3",
    "colorNames": [
      "Black",
      "White",
      "Blue"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 1749,
        "verified": true
      }
    ]
  },
  "oneplus-nord-5": {
    "brand": "OnePlus",
    "name": "OnePlus Nord 5",
    
    "flipkartUrl": "https://www.flipkart.com/oneplus-nord-55g-marble-sands-256-gb/p/itmfd2cc9a18a7be",
    "colorNames": [
      "Marble Sands",
      "Phantom Grey",
      "Dry Ice"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "oneplus-nord-6": {
    "brand": "OnePlus",
    "name": "OnePlus Nord 6",
    "flipkartUrl": "https://www.flipkart.com/oneplus-nord-6-fresh-mint-256-gb/p/itmc49f71cdc4080",
"colorNames": [
      "Stormy Black",
      "Misty Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 49472,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 54472,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 59472,
        "verified": true
      }
    ]
  },
  "oneplus-nord-ce6": {
    "brand": "OnePlus",
    "name": "OnePlus Nord CE6",
    "flipkartUrl": "https://www.flipkart.com/oneplus-nord-ce6-pitch-black-128-gb/p/itmd7b224b18cb05",
"colorNames": [
      "Dark Chrome",
      "Cloud Trinity"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 35850,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 40850,
        "verified": true
      }
    ]
  },
  "oneplus-nord-ce6-lite": {
    "brand": "OnePlus",
    "name": "OnePlus Nord CE6 Lite",
    "flipkartUrl": "https://www.flipkart.com/oneplus-nord-ce6-lite-vivid-mint-128-gb/p/itm21e965b5b799d",
"colorNames": [
      "Pastel Lime",
      "Aqua Surge"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 31927,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 35927,
        "verified": true
      }
    ]
  },
  "oneplus-pad-go-2": {
    "brand": "OnePlus",
    "name": "OnePlus Pad Go 2",
    "colorNames": [
      "Mint Green",
      "Space Grey"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 31499,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 36499,
        "verified": true
      }
    ]
  },
  "oppo-a6x": {
    "brand": "Oppo",
    "name": "Oppo A6x",
    "flipkartUrl": "https://www.flipkart.com/oppo-a6x-5g-ice-blue-64-gb/p/itmdf1381e11e8a7",
"colorNames": [
      "Starlight White",
      "Midnight Black",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 17999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20999,
        "verified": true
      }
    ]
  },
  "oppo-f31-pro-plus": {
    "brand": "Oppo",
    "name": "Oppo F31 Pro Plus",
    
    "amazonUrl": "https://www.amazon.in/Oppo-Gemstone-Blue-256GB-Storage/dp/B0FP8MCBT8",
    "colorNames": [
      "Astral Blue",
      "Stellar Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 34999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 39999,
        "verified": true
      }
    ]
  },
  "oppo-f33": {
    "brand": "Oppo",
    "name": "Oppo F33",
    
    "flipkartUrl": "https://www.flipkart.com/oppo-f33-5g-forest-green-128-gb/p/itm8c5d4a65602fd",
    "colorNames": [
      "Misty Forest",
      "Passion Red",
      "Starry Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 36999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      }
    ]
  },
  "oppo-f33-pro": {
    "brand": "Oppo",
    "name": "Oppo F33 Pro",
    "flipkartUrl": "https://www.flipkart.com/oppo-f33-pro-5g-misty-forest-256-gb/p/itme0e9af182d309",
"colorNames": [
      "Misty Forest",
      "Passion Red",
      "Starry Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 43999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "oppo-k13": {
    "brand": "Oppo",
    "name": "Oppo K13",
    "flipkartUrl": "https://www.flipkart.com/oppo-k13-5g-7000mah-80w-supervooc-charger-in-the-box-prism-black-128-gb/p/itm6f2ebf6d205cf",
"colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 23999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      }
    ]
  },
  "oppo-k13x": {
    "brand": "Oppo",
    "name": "Oppo K13x",
    "flipkartUrl": "https://www.flipkart.com/oppo-k13x-5g-6000mah-45w-supervooc-charger-ai-midnight-violet-128-gb/p/itm62b2e62fbb43e",
"colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "oppo-k14": {
    "brand": "Oppo",
    "name": "Oppo K14",
    "flipkartUrl": "https://www.flipkart.com/oppo-k14-5g-prism-violet-128-gb/p/itm2a5cc1d23c2af",
"colorNames": [
      "Iron Grey",
      "Ice Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 21999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 25999,
        "verified": true
      }
    ]
  },
  "oppo-k14x": {
    "brand": "Oppo",
    "name": "Oppo K14x",
    "flipkartUrl": "https://www.flipkart.com/oppo-k14x-5g-icy-blue-64-gb/p/itm188c7a4b69292",
"colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 19999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      }
    ]
  },
  "oppo-reno-15": {
    "brand": "Oppo",
    "name": "Oppo Reno 15",
    "flipkartUrl": "https://www.flipkart.com/oppo-reno15-5g-aurora-blue-256-gb/p/itm37cc91d1c2807",
"colorNames": [
      "Silver Moon",
      "Midnight Black",
      "Aurora Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 47999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 54999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 59999,
        "verified": true
      }
    ]
  },
  "oppo-reno-15-pro-mini": {
    "brand": "Oppo",
    "name": "Oppo Reno 15 Pro Mini",
    
    "amazonUrl": "https://www.amazon.in/Reno15Pro-Glacier-Storage-Additional-Exchange/dp/B0G8YX1HVK",
    "colorNames": [
      "Space Silver",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 64999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 74999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 89999,
        "verified": true
      }
    ]
  },
  "oppo-reno-15c": {
    "brand": "Oppo",
    "name": "Oppo Reno 15C",
    "colorNames": [
      "Starlight White",
      "Midnight Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 41999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "poco-c71": {
    "brand": "POCO",
    "name": "POCO C71",
    "flipkartUrl": "https://www.flipkart.com/poco-c71-desert-gold-64-gb/p/itme3dc58af6a04b",
"colorNames": [
      "Power Black",
      "Coral Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 9999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11999,
        "verified": true
      }
    ]
  },
  "poco-c85": {
    "brand": "POCO",
    "name": "POCO C85",
    "flipkartUrl": "https://www.flipkart.com/poco-c85-5g-mystic-purple-128-gb/p/itm74e2143a5de24",
"colorNames": [
      "Power Black",
      "Coral Green"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 19499,
        "verified": true
      }
    ]
  },
  "poco-c85x": {
    "brand": "POCO",
    "name": "POCO C85x",
    "colorNames": [
      "Power Black",
      "Coral Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      }
    ]
  },
  "poco-m7": {
    "brand": "POCO",
    "name": "POCO M7",
    "flipkartUrl": "https://www.flipkart.com/poco-m7-5g/p/itmf030852464eef",
"colorNames": [
      "Graphite Black",
      "Aurora Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 13499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 16499,
        "verified": true
      }
    ]
  },
  "poco-m7-plus": {
    "brand": "POCO",
    "name": "POCO M7 Plus",
    "flipkartUrl": "https://www.flipkart.com/poco-m7-plus-5g-chrome-silver-128-gb/p/itm2fbc82f08965c",
"colorNames": [
      "Graphite Black",
      "Aurora Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 21999,
        "verified": true
      }
    ]
  },
  "realme-15": {
    "brand": "Realme",
    "name": "Realme 15",
    "flipkartUrl": "https://www.flipkart.com/realme-15-5g-silk-pink-256-gb/p/itme9581fbd0e97a",
"colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 32499,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 37499,
        "verified": true
      }
    ]
  },
  "realme-15t": {
    "brand": "Realme",
    "name": "Realme 15T",
    "flipkartUrl": "https://www.flipkart.com/realme-15t-5g-flowing-silver-128-gb/p/itm3f28d98da183c",
"colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "realme-15x": {
    "brand": "Realme",
    "name": "Realme 15x",
    "flipkartUrl": "https://www.flipkart.com/realme-15x-5g-aqua-blue-128-gb/p/itmcf22f2a57724f",
"colorNames": [
      "Speed Green",
      "Racing Black",
      "Champion Gold"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 25999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28999,
        "verified": true
      }
    ]
  },
  "realme-16": {
    "brand": "Realme",
    "name": "Realme 16",
    "amazonUrl": "https://www.amazon.in/realme-Smartphone-6-57-inch-Front50MP-Dimensity/dp/B0GTV1784Z",
    "flipkartUrl": "https://www.flipkart.com/realme-16-5g-air-black-256-gb/p/itm7b0c4cd95742b",
"colorNames": [
      "Pebble Grey",
      "Master Gold",
      "Orchid Purple"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 35999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 40999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 45999,
        "verified": true
      }
    ]
  },
  "realme-16-pro": {
    "brand": "Realme",
    "name": "Realme 16 Pro+",
    "amazonUrl": "https://www.amazon.in/realme-16-Pro-Smartphone-Snapdragon/dp/B0GC6N68BC",
    "flipkartUrl": "https://www.flipkart.com/realme-16-pro-5g/p/itmf8e5c193facd1",
"colorNames": [
      "Master Grey",
      "Master Gold",
      "Camellia Pink"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 55999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 60999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 65999,
        "verified": true
      }
    ]
  },
  "realme-16t": {
    "brand": "Realme",
    "name": "Realme 16T",
    
    "amazonUrl": "https://www.amazon.in/dp/B0H255CF45",
    "flipkartUrl": "https://www.flipkart.com/realme-16t-5g-aurora-green-256-gb/p/itm604f2af610fd0",
    "colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "realme-c71": {
    "brand": "Realme",
    "name": "Realme C71",
    "amazonUrl": "https://www.amazon.in/realme-Smartphone-Comfort-Display-Obsidian/dp/B0GFVPT1X9",
    "flipkartUrl": "https://www.flipkart.com/realme-c71-sea-blue-128-gb/p/itm920c5c8761871",
"colorNames": [
      "Meadow Green",
      "Twilight Purple"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12869,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14869,
        "verified": true
      }
    ]
  },
  "realme-c83": {
    "brand": "Realme",
    "name": "Realme C83",
    "amazonUrl": "https://www.amazon.in/realme-Smartphone-Dimensity-Processor-Waterproof/dp/B0GQ78KNPT",
    "flipkartUrl": "https://www.flipkart.com/realme-c83-5g-sprouting-green-64-gb/p/itm85479b4419036",
"colorNames": [
      "Meadow Green",
      "Twilight Purple"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 173,
        "verified": true
      }
    ]
  },
  "realme-p3x": {
    "brand": "Realme",
    "name": "Realme P3x",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "realme-p4": {
    "brand": "Realme",
    "name": "Realme P4",
    "amazonUrl": "https://www.amazon.in/realme-P4-Smartphone-Engine-128-0/dp/B0FMDXKDDF",
"colorNames": [
      "Nebula Purple",
      "Cosmic Black",
      "Starlight Silver"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "realme-p4-lite": {
    "brand": "Realme",
    "name": "Realme P4 Lite",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      }
    ]
  },
  "realme-p4-power": {
    "brand": "Realme",
    "name": "Realme P4 Power",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "realme-p4x": {
    "brand": "Realme",
    "name": "Realme P4x",
    "amazonUrl": "https://www.amazon.in/realme-P4X-Smartphone-Dimensity-Waterproof/dp/B0G3X99MZS",
"colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 20499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 23499,
        "verified": true
      }
    ]
  },
  "realme-pad-2-lite": {
    "brand": "Realme",
    "name": "Realme Pad 2 Lite",
    "amazonUrl": "https://www.amazon.in/realme-10-9Inch-Eyecomfort-Mediatek-Connectivity/dp/B0DHQTQYNR",
"colorNames": [
      "Green",
      "Grey"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 21999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 25999,
        "verified": true
      }
    ]
  },
  "redmi-15a": {
    "brand": "Redmi",
    "name": "Redmi 15A",
    "flipkartUrl": "https://www.flipkart.com/redmi-15a-awesome-blue-128-gb/p/itm9217bed9d5ed2",
"colorNames": [
      "Light Blue",
      "Black",
      "Green"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 14859,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16859,
        "verified": true
      }
    ]
  },
  "redmi-15c": {
    "brand": "Redmi",
    "name": "Redmi 15C",
    "flipkartUrl": "https://www.flipkart.com/redmi-15c-5g-dusk-purple-128-gb/p/itma65eb003483e4",
"colorNames": [
      "Stardust Purple",
      "Midnight Black",
      "Forest Green"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      }
    ]
  },
  "redmi-a4": {
    "brand": "Redmi",
    "name": "Redmi A4",
    "amazonUrl": "https://www.amazon.in/Redmi-A4-5G-Sparkle-Charging/dp/B0FBR69B2R",
    "flipkartUrl": "https://www.flipkart.com/redmi-a4-sparkle-purple-128-gb/p/itm195b57bdc2f83",
"colorNames": [
      "Midnight Black",
      "Starlight Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      }
    ]
  },
  "redmi-a5": {
    "brand": "Redmi",
    "name": "Redmi A5",
    "flipkartUrl": "https://www.flipkart.com/redmi-a5-jaisalmer-gold-64-gb/p/itm2b4357effaa74",
"colorNames": [
      "Midnight Black",
      "Lake Blue",
      "Olive Green"
    ],
    "variants": [
      {
        "ram": "3GB",
        "storage": "64GB",
        "price": 8699,
        "verified": true
      },
      {
        "ram": "4GB",
        "storage": "128GB",
        "price": 10699,
        "verified": true
      }
    ]
  },
  "redmi-a7-pro": {
    "brand": "Redmi",
    "name": "Redmi A7 Pro",
    "colorNames": [
      "Midnight Black",
      "Starlight Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 17999,
        "verified": true
      }
    ]
  },
  "samsung-a06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy A06",
    "amazonUrl": "https://www.amazon.in/Samsung-Galaxy-Storage-MediaTek-Battery/dp/B0DCJMMGNF",
"colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 10738,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 12738,
        "verified": true
      }
    ]
  },
  "samsung-f06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F06",
    "amazonUrl": "https://www.amazon.in/Samsung-Galaxy-Bahama-Blue-128GB/dp/B0DYKC512N",
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-f06-5g-bahama-blue-128-gb/p/itm9acd4c5748761",
"colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      }
    ]
  },
  "samsung-f07": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F07",
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-f07-green-64-gb/p/itm294cbb65839e6",
"colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 11999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 13999,
        "verified": true
      }
    ]
  },
  "samsung-f36": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F36",
    "amazonUrl": "https://www.amazon.in/Samsung-Galaxy-F36-Black-128GB/dp/B0FLZ517QL",
"colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 25499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28499,
        "verified": true
      }
    ]
  },
  "samsung-f70e": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F70e",
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-f70e-5g-spotlight-blue-128-gb/p/itm9b75b980e9dae",
"colorNames": [
      "Awesome Graphite",
      "Awesome Silver"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 17499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20499,
        "verified": true
      }
    ]
  },
  "samsung-m06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M06",
    "amazonUrl": "https://www.amazon.in/Samsung-MediaTek-Dimensity-Charging-Upgrades/dp/B0DX6P3RX9",
    "flipkartUrl": "https://www.flipkart.com/samsung-m06-5g-blazing-black-128-gb/p/itmcafa42dadc15c",
"colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13470,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15470,
        "verified": true
      }
    ]
  },
  "samsung-m36": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M36",
    "amazonUrl": "https://www.amazon.in/Samsung-Storage-Enhanced-Unmatched-Nightography/dp/B0FDB9H277",
    "flipkartUrl": "https://www.flipkart.com/samsung-m36-5g-light-green-128-gb/p/itm4cf1eae54334f",
"colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 19647,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22647,
        "verified": true
      }
    ]
  },
  "samsung-m56": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M56",
    "amazonUrl": "https://www.amazon.in/Samsung-Slimmest-Enhanced-Nightography-Processor/dp/B0F43WXC8K",
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-m56-5g-black-128-gb/p/itm64935225a672e",
"colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 25925,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 30925,
        "verified": true
      }
    ]
  },
  "samsung-s25-fe": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S25 FE",
    "amazonUrl": "https://www.amazon.in/Samsung-Smartphone-JetBlack-Storage-ProVisual/dp/B0FNMQW9HW",
"colorNames": [
      "Icyblue",
      "Jetblack",
      "Navy",
      "White"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 77999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 84999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "512GB",
        "price": 94999,
        "verified": true
      }
    ]
  },
  "samsung-s25-ultra": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S25 Ultra",
    "amazonUrl": "https://www.amazon.in/Samsung-Smartphone-Silverblue-Snapdragon-ProVisual/dp/B0DSBTKP5Q",
    "flipkartUrl": "https://www.flipkart.com/samsung-galaxy-s25-ultra-5g-titanium-black-256-gb/p/itm09d676ceb930d",
"colorNames": [
      "Titanium Silverblue",
      "Titanium Black",
      "Titanium Gray",
      "Titanium Whitesilver"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 129990,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 139990,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 159990,
        "verified": true
      }
    ]
  },
  "samsung-s26-plus": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S26+",
    "amazonUrl": "https://www.amazon.in/Samsung-Storage-Creative-Wireless-Charging/dp/B0GL8J486T",
"colorNames": [
      "Black",
      "Cobalt Violet",
      "Sky Blue",
      "White",
      "Pink Gold (Online Exclusive)",
      "Silver Shadow (Online Exclusive)"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 114999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 124999,
        "verified": true
      }
    ]
  },
  "samsung-tab-s10-lite": {
    "brand": "Samsung",
    "name": "Samsung Galaxy Tab S10 Lite",
    "amazonUrl": "https://www.amazon.in/Samsung-Galaxy-Display-Refresh-Storage/dp/B0FNWNZZ1B",
"colorNames": [
      "Graphite",
      "Silver",
      "Pink Gold"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 30140,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 35140,
        "verified": true
      }
    ]
  },
  "vivo-t4": {
    "brand": "Vivo",
    "name": "Vivo T4",
    "flipkartUrl": "https://www.flipkart.com/vivo-t4-5g-emerald-blaze-128-gb/p/itmc2634fd4daeb9",
"colorNames": [
      "Emerald Blaze",
      "Phantom Grey"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 28999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 33999,
        "verified": true
      }
    ]
  },
  "vivo-t4-lite": {
    "brand": "Vivo",
    "name": "Vivo T4 Lite",
    "flipkartUrl": "https://www.flipkart.com/vivo-t4-lite-5g-2026-titanium-gold-128-gb/p/itm08f41580b36a4",
"colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 23999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      }
    ]
  },
  "vivo-t4-pro": {
    "brand": "Vivo",
    "name": "Vivo T4 Pro",
    "amazonUrl": "https://www.amazon.in/vivo-T4-Pro-5G-Blaze/dp/B0G4QQ3ZFV",
    "flipkartUrl": "https://www.flipkart.com/vivo-t4-pro-5g-nitro-blue-128-gb/p/itm4da1824b696d9",
"colorNames": [
      "Nitro Blue",
      "Blaze Gold"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "vivo-t4-ultra": {
    "brand": "Vivo",
    "name": "Vivo T4 Ultra",
    "amazonUrl": "https://www.amazon.in/VIVO-T4-Ultra-5G-Meteor/dp/B0FFB1L75V",
    "flipkartUrl": "https://www.flipkart.com/vivo-t4-ultra-5g-meteor-grey-512-gb/p/itm9cfd8118c9ce0",
"colorNames": [
      "Phoenix Gold",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "vivo-t4r": {
    "brand": "Vivo",
    "name": "Vivo T4R",
    "amazonUrl": "https://www.amazon.in/VIVO-T4R-Twilight-Blue-256GB/dp/B0FPGR6SJ5",
    "flipkartUrl": "https://www.flipkart.com/vivo-t4r-5g-twilight-blue-128-gb/p/itm3a5653667cb9c",
"colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28999,
        "verified": true
      }
    ]
  },
  "vivo-t4x": {
    "brand": "Vivo",
    "name": "Vivo T4x",
    "amazonUrl": "https://www.amazon.in/Mobile-Phone-T4x-Marine-Blue_128G/dp/B0F194NC2H",
    "flipkartUrl": "https://www.flipkart.com/vivo-t4x-5g-marine-blue-128-gb/p/itm017656bdd097b",
"colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      }
    ]
  },
  "vivo-t5-pro": {
    "brand": "Vivo",
    "name": "Vivo T5 Pro",
    "flipkartUrl": "https://www.flipkart.com/vivo-t5-pro-5g-glacier-blue-128-gb/p/itma21e2e09d4493",
"colorNames": [
      "Glacier Blue",
      "Starry Black",
      "Champagne Gold"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "vivo-t5x": {
    "brand": "Vivo",
    "name": "Vivo T5x",
    "amazonUrl": "https://www.amazon.in/vivo-5G-Dimensity-7400-Turbo-Processor/dp/B0GXRVCPST",
    "flipkartUrl": "https://www.flipkart.com/vivo-t5x-5g-star-silver-128-gb/p/itm7da8aa253e72b",
"colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28999,
        "verified": true
      }
    ]
  },
  "vivo-v70": {
    "brand": "Vivo",
    "name": "Vivo V70",
    "flipkartUrl": "https://www.flipkart.com/vivo-v70-passion-red-256-gb/p/itmecfa7a31699de",
"colorNames": [
      "Starry Black",
      "Titanium Silver",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 53999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 60999,
        "verified": true
      }
    ]
  },
  "vivo-v70-elite": {
    "brand": "Vivo",
    "name": "Vivo V70 Elite",
    "flipkartUrl": "https://www.flipkart.com/vivo-v70-elite-passion-red-2026-256-gb/p/itmf8e28e33a9cd0",
"colorNames": [
      "Starry Black",
      "Titanium Silver",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 58999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 66999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 78999,
        "verified": true
      }
    ]
  },
  "vivo-v70-fe": {
    "brand": "Vivo",
    "name": "Vivo V70 FE",
    "flipkartUrl": "https://www.flipkart.com/vivo-v70-fe-northern-lights-purple-256-gb/p/itmda852a903ef97",
"colorNames": [
      "Jade Green",
      "Coral Red"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "vivo-y05": {
    "brand": "Vivo",
    "name": "Vivo Y05",
    "flipkartUrl": "https://www.flipkart.com/vivo-y05-champagne-gold-64-gb/p/itm7b1e1a65e7c1f",
"colorNames": [
      "Midnight Black",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      }
    ]
  },
  "vivo-y11": {
    "brand": "Vivo",
    "name": "Vivo Y11",
    "flipkartUrl": "https://www.flipkart.com/vivo-y11-5g-midnight-blue-64-gb/p/itm722b8f27be0b8",
"colorNames": [
      "Midnight Black",
      "Ocean Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "vivo-y31": {
    "brand": "Vivo",
    "name": "Vivo Y31",
    "flipkartUrl": "https://www.flipkart.com/vivo-y31-racing-black-128-gb/p/itm4d669e9668d87",
"colorNames": [
      "Starry Black",
      "Champagne Gold"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 25999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      }
    ]
  },
  "vivo-y51-pro": {
    "brand": "Vivo",
    "name": "Vivo Y51 Pro",
    
    "flipkartUrl": "https://www.flipkart.com/vivo-y51-pro-5g-festive-red-128-gb/p/itmed4b902ad17d9",
    "colorNames": [
      "Starry Black",
      "Champagne Gold",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 33999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 39999,
        "verified": true
      }
    ]
  },
  "iqoo-15": {
    "brand": "iQOO",
    "name": "iQOO 15",
    "amazonUrl": "https://www.amazon.in/iQOO-Storage-Fastest-Snapdragon-Processor/dp/B0FYGBSKFB",
    "colorNames": [
      "Alpha",
      "Legend",
      "Gray",
      "Green",
      "Blue",
      "Apex"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 76999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 86999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 101999,
        "verified": true
      }
    ]
  },
  "iqoo-15r": {
    "brand": "iQOO",
    "name": "iQOO 15R",
    "amazonUrl": "https://www.amazon.in/iQOO-Snapdragon%C2%AE-Processor-Slimmest-Smartphone/dp/B0GL83ZTP8",
    "flipkartUrl": "https://www.flipkart.com/iqoo-15r-5g-dark-knight-256-gb/p/itm7bc8aee18f590",
    "colorNames": [
      "Raging Blue",
      "MoonKnight",
      "Titanium"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 49999,
        "verified": true
      }
    ]
  },
  "iqoo-neo-10": {
    "brand": "iQOO",
    "name": "iQOO Neo 10",
    "amazonUrl": "https://www.amazon.in/iQOO-Processor-Snapdragon-Supercomputing-FlashCharge/dp/B0GXZ1VC4J",
    "colorNames": [
      "Inferno Red",
      "Titanium Chrome",
      "Blaze Orange",
      "Onyx Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 41999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 54999,
        "verified": true
      }
    ]
  },
  "iqoo-z10-lite": {
    "brand": "iQOO",
    "name": "iQOO Z10 Lite",
    "amazonUrl": "https://www.amazon.in/iQOO-Lite-Titanium-Blue-Storage/dp/B0H1JG89ZB",
    "colorNames": [
      "Storm Black",
      "Cyber Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 19999,
        "verified": true
      }
    ]
  },
  "iqoo-z10r": {
    "brand": "iQOO",
    "name": "iQOO Z10R",
    "amazonUrl": "https://www.amazon.in/iQOO-Aquamarine-Quad-Curved-Dimensity-Processor/dp/B0FHB5V36G",
    "flipkartUrl": "https://www.flipkart.com/iqoo-z10r-5g-8gb-256gb-moonstone-moonstone-256-gb/p/itm787d52a4e214e",
    "colorNames": [
      "Storm Black",
      "Cyber Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 22999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 26999,
        "verified": true
      }
    ]
  },
  "iqoo-z11x": {
    "brand": "iQOO",
    "name": "iQOO Z11x",
    "amazonUrl": "https://www.amazon.in/iQOO-Prismatic-Dimensity-7400-Turbo-Processor/dp/B0GP8XYL7H",
    "colorNames": [
      "Storm Black",
      "Cyber Blue",
      "Neon Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "nothing-phone-4a": {
    "brand": "Nothing",
    "name": "Nothing Phone 4a",
    "flipkartUrl": "https://www.flipkart.com/nothing-phone-4a-white-128-gb/p/itm47712249513d4",
    "colorNames": [
      "White",
      "Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
};

export const DIRECT_URLS_META = {
  "generatedAt": "2026-07-16T10:41:38.997Z",
  "source": "C:\\Users\\ramak\\Downloads\\products_with_direct_urls.csv",
  "matched": 107,
  "unknown": [],
  "searchUrls": [],
  "totalVariants": 225
};
