// AUTO-GENERATED by scripts/build-direct-urls-data.ts from C:\Users\ramak\Downloads\products_with_direct_urls.csv
// Do not edit by hand. Re-run `npm run direct-urls:build` to regenerate.
import type { DirectUrlProduct } from "./direct-urls-parse";

export const DIRECT_URLS_BY_SLUG: Record<string, DirectUrlProduct> = {
  "airpods-4": {
    "brand": "Apple",
    "name": "Apple AirPods 4",
    "colorNames": [
      "White (Standard)"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 17900,
        "verified": true
      }
    ]
  },
  "iphone-17": {
    "brand": "Apple",
    "name": "iPhone 17",
    "colorNames": [
      "Lavender",
      "Sage",
      "Mist Blue",
      "White",
      "Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 82900,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "512GB",
        "price": 92900,
        "verified": true
      }
    ]
  },
  "iphone-17-air": {
    "brand": "Apple",
    "name": "iPhone 17 Air",
    "colorNames": [
      "Sky Blue",
      "Light Gold",
      "Cloud White",
      "Space Black"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 99900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 109900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "1TB",
        "price": 129900,
        "verified": true
      }
    ]
  },
  "iphone-17-pro": {
    "brand": "Apple",
    "name": "iPhone 17 Pro",
    "colorNames": [
      "Cosmic Orange",
      "Deep Blue",
      "Silver"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 132900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 142900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "1TB",
        "price": 162900,
        "verified": true
      }
    ]
  },
  "iphone-17-pro-max": {
    "brand": "Apple",
    "name": "iPhone 17 Pro Max",
    "colorNames": [
      "Silver",
      "Cosmic Orange",
      "Deep Blue"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 101900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 111900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "1TB",
        "price": 131900,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "2TB",
        "price": 151900,
        "verified": true
      }
    ]
  },
  "pixel-10": {
    "brand": "Google",
    "name": "Google Pixel 10",
    "colorNames": [
      "Indigo",
      "Frost",
      "Lemongrass",
      "Obsidian"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "128GB",
        "price": 74999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 84999,
        "verified": true
      }
    ]
  },
  "pixel-10a": {
    "brand": "Google",
    "name": "Google Pixel 10a",
    "colorNames": [
      "Obsidian",
      "Porcelain",
      "Aloe",
      "Bay"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 49999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 59999,
        "verified": true
      }
    ]
  },
  "hmd-vibe-2": {
    "brand": "HMD",
    "name": "HMD Vibe 2",
    "colorNames": [
      "Cosmic Lavender",
      "Nordic Blue",
      "Peach Pink"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      }
    ]
  },
  "infinix-gt-30": {
    "brand": "Infinix",
    "name": "Infinix GT 30",
    "colorNames": [
      "Pulse Green",
      "Cyber Blue",
      "Blade White"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20999,
        "verified": true
      }
    ]
  },
  "infinix-gt-30-pro": {
    "brand": "Infinix",
    "name": "Infinix GT 30 Pro",
    "colorNames": [
      "Dark Flare",
      "Blade White",
      "Shadow Ash"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 26999,
        "verified": true
      }
    ]
  },
  "infinix-note-edge": {
    "brand": "Infinix",
    "name": "Infinix Note Edge",
    "colorNames": [
      "Shadow Black",
      "Solar Orange",
      "Lunar Titanium",
      "Silk Green",
      "Stellar Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 16999,
        "verified": true
      }
    ]
  },
  "infinix-smart-10": {
    "brand": "Infinix",
    "name": "Infinix Smart 10",
    "colorNames": [
      "Black",
      "Blue",
      "Green"
    ],
    "variants": [
      {
        "ram": "3GB",
        "storage": "64GB",
        "price": 6499,
        "verified": true
      },
      {
        "ram": "4GB",
        "storage": "128GB",
        "price": 7499,
        "verified": true
      }
    ]
  },
  "infinix-smart-20": {
    "brand": "Infinix",
    "name": "Infinix Smart 20",
    "colorNames": [
      "Sunlit Orange",
      "Black",
      "Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 6999,
        "verified": true
      },
      {
        "ram": "4GB",
        "storage": "128GB",
        "price": 7999,
        "verified": true
      }
    ]
  },
  "moto-60-fusion": {
    "brand": "Motorola",
    "name": "Motorola 60 Fusion",
    "colorNames": [
      "Eclipse Black",
      "Marshmallow Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      }
    ]
  },
  "moto-70-fusion": {
    "brand": "Motorola",
    "name": "Motorola 70 Fusion",
    "colorNames": [
      "Koala Grey",
      "Ballad Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 33999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 38999,
        "verified": true
      }
    ]
  },
  "moto-edge-60": {
    "brand": "Motorola",
    "name": "Motorola Edge 60",
    "colorNames": [
      "Koala Grey",
      "Ballad Blue",
      "Pantone Nautical Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "moto-edge-60-pro": {
    "brand": "Motorola",
    "name": "Motorola Edge 60 Pro",
    "colorNames": [
      "Pantone Nautical Blue",
      "Pantone Gibraltar Sea"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "moto-edge-70-pro": {
    "brand": "Motorola",
    "name": "Motorola Edge 70 Pro",
    "colorNames": [
      "Pantone Lily White",
      "Pantone Titan",
      "Pantone Tea",
      "Pantone Zinfandel",
      "Pantone Chicory Coffee"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 44999,
        "verified": true
      }
    ]
  },
  "moto-g06-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G06 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      }
    ]
  },
  "moto-g37": {
    "brand": "Motorola",
    "name": "Motorola Moto G37",
    "colorNames": [
      "Ocean Blue",
      "Charcoal Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 10000,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11999,
        "verified": true
      }
    ]
  },
  "moto-g37-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G37 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "moto-g57-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G57 Power",
    "colorNames": [
      "Sage Green",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 20999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 23999,
        "verified": true
      }
    ]
  },
  "moto-g67-power": {
    "brand": "Motorola",
    "name": "Motorola Moto G67 Power",
    "colorNames": [
      "Ocean Blue",
      "Charcoal Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 10000,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11999,
        "verified": true
      }
    ]
  },
  "moto-g96": {
    "brand": "Motorola",
    "name": "Motorola Moto G96",
    "colorNames": [
      "Sage Green",
      "Meteor Grey",
      "Ballad Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 24999,
        "verified": true
      }
    ]
  },
  "narzo-100-lite": {
    "brand": "Narzo",
    "name": "Realme Narzo 100 Lite",
    "colorNames": [
      "Frost Silver",
      "Thunder Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 18320,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 20320,
        "verified": true
      }
    ]
  },
  "narzo-80-lite": {
    "brand": "Narzo",
    "name": "Realme Narzo 80 Lite",
    "colorNames": [
      "Beach Gold",
      "Obsidian Black",
      "Crystal Purple"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      }
    ]
  },
  "narzo-90": {
    "brand": "Narzo",
    "name": "Realme Narzo 90",
    "colorNames": [
      "Victory Gold",
      "Carbon Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "narzo-90x": {
    "brand": "Narzo",
    "name": "Realme Narzo 90x",
    "colorNames": [
      "Flash Blue",
      "Nitro Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 19998,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 21998,
        "verified": true
      }
    ]
  },
  "narzo-n53": {
    "brand": "Narzo",
    "name": "Realme Narzo N53",
    "colorNames": [
      "Feather Gold",
      "Feather Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 9887,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11887,
        "verified": true
      }
    ]
  },
  "narzo-power": {
    "brand": "Narzo",
    "name": "Realme Narzo Power",
    "colorNames": [
      "Titan Silver",
      "Titan Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 37998,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 41998,
        "verified": true
      }
    ]
  },
  "oneplus-13": {
    "brand": "OnePlus",
    "name": "OnePlus 13",
    "colorNames": [
      "Midnight Ocean",
      "Arctic Dawn",
      "Black Eclipse"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 57999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 67999,
        "verified": true
      },
      {
        "ram": "24GB",
        "storage": "1TB",
        "price": 82999,
        "verified": true
      }
    ]
  },
  "oneplus-z2-anc": {
    "brand": "OnePlus",
    "name": "OnePlus Buds Z2 ANC",
    "colorNames": [
      "Black",
      "White"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 999,
        "verified": true
      }
    ]
  },
  "oneplus-z3": {
    "brand": "OnePlus",
    "name": "OnePlus Buds Z3",
    "colorNames": [
      "Black",
      "White",
      "Blue"
    ],
    "variants": [
      {
        "ram": "",
        "storage": "",
        "price": 1749,
        "verified": true
      }
    ]
  },
  "oneplus-nord-5": {
    "brand": "OnePlus",
    "name": "OnePlus Nord 5",
    "colorNames": [
      "Marble Sands",
      "Phantom Grey",
      "Dry Ice"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "oneplus-nord-6": {
    "brand": "OnePlus",
    "name": "OnePlus Nord 6",
    "colorNames": [
      "Stormy Black",
      "Misty Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 49472,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 54472,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 59472,
        "verified": true
      }
    ]
  },
  "oneplus-nord-ce6": {
    "brand": "OnePlus",
    "name": "OnePlus Nord CE6",
    "colorNames": [
      "Dark Chrome",
      "Cloud Trinity"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 35850,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 40850,
        "verified": true
      }
    ]
  },
  "oneplus-nord-ce6-lite": {
    "brand": "OnePlus",
    "name": "OnePlus Nord CE6 Lite",
    "colorNames": [
      "Pastel Lime",
      "Aqua Surge"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 31927,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 35927,
        "verified": true
      }
    ]
  },
  "oneplus-pad-go-2": {
    "brand": "OnePlus",
    "name": "OnePlus Pad Go 2",
    "colorNames": [
      "Mint Green",
      "Space Grey"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 31499,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 36499,
        "verified": true
      }
    ]
  },
  "oppo-a6x": {
    "brand": "Oppo",
    "name": "Oppo A6x",
    "colorNames": [
      "Starlight White",
      "Midnight Black",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 17999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20999,
        "verified": true
      }
    ]
  },
  "oppo-f31-pro-plus": {
    "brand": "Oppo",
    "name": "Oppo F31 Pro Plus",
    "colorNames": [
      "Astral Blue",
      "Stellar Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 34999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 39999,
        "verified": true
      }
    ]
  },
  "oppo-f33": {
    "brand": "Oppo",
    "name": "Oppo F33",
    "colorNames": [
      "Misty Forest",
      "Passion Red",
      "Starry Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 36999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      }
    ]
  },
  "oppo-f33-pro": {
    "brand": "Oppo",
    "name": "Oppo F33 Pro",
    "colorNames": [
      "Misty Forest",
      "Passion Red",
      "Starry Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 43999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "oppo-k13": {
    "brand": "Oppo",
    "name": "Oppo K13",
    "colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 23999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      }
    ]
  },
  "oppo-k13x": {
    "brand": "Oppo",
    "name": "Oppo K13x",
    "colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "oppo-k14": {
    "brand": "Oppo",
    "name": "Oppo K14",
    "colorNames": [
      "Iron Grey",
      "Ice Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 21999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 25999,
        "verified": true
      }
    ]
  },
  "oppo-k14x": {
    "brand": "Oppo",
    "name": "Oppo K14x",
    "colorNames": [
      "Iron Grey",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 19999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      }
    ]
  },
  "oppo-reno-15": {
    "brand": "Oppo",
    "name": "Oppo Reno 15",
    "colorNames": [
      "Silver Moon",
      "Midnight Black",
      "Aurora Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 47999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 54999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 59999,
        "verified": true
      }
    ]
  },
  "oppo-reno-15-pro-mini": {
    "brand": "Oppo",
    "name": "Oppo Reno 15 Pro Mini",
    "colorNames": [
      "Space Silver",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 64999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 74999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 89999,
        "verified": true
      }
    ]
  },
  "oppo-reno-15c": {
    "brand": "Oppo",
    "name": "Oppo Reno 15C",
    "colorNames": [
      "Starlight White",
      "Midnight Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 41999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "poco-c71": {
    "brand": "POCO",
    "name": "POCO C71",
    "colorNames": [
      "Power Black",
      "Coral Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 9999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 11999,
        "verified": true
      }
    ]
  },
  "poco-c85": {
    "brand": "POCO",
    "name": "POCO C85",
    "colorNames": [
      "Power Black",
      "Coral Green"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 19499,
        "verified": true
      }
    ]
  },
  "poco-c85x": {
    "brand": "POCO",
    "name": "POCO C85x",
    "colorNames": [
      "Power Black",
      "Coral Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      }
    ]
  },
  "poco-m7": {
    "brand": "POCO",
    "name": "POCO M7",
    "colorNames": [
      "Graphite Black",
      "Aurora Green",
      "Ice Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 13499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 16499,
        "verified": true
      }
    ]
  },
  "poco-m7-plus": {
    "brand": "POCO",
    "name": "POCO M7 Plus",
    "colorNames": [
      "Graphite Black",
      "Aurora Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 21999,
        "verified": true
      }
    ]
  },
  "realme-15": {
    "brand": "Realme",
    "name": "Realme 15",
    "colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 32499,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 37499,
        "verified": true
      }
    ]
  },
  "realme-15t": {
    "brand": "Realme",
    "name": "Realme 15T",
    "colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "realme-15x": {
    "brand": "Realme",
    "name": "Realme 15x",
    "colorNames": [
      "Speed Green",
      "Racing Black",
      "Champion Gold"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 25999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28999,
        "verified": true
      }
    ]
  },
  "realme-16": {
    "brand": "Realme",
    "name": "Realme 16",
    "colorNames": [
      "Pebble Grey",
      "Master Gold",
      "Orchid Purple"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 35999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 40999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 45999,
        "verified": true
      }
    ]
  },
  "realme-16-pro": {
    "brand": "Realme",
    "name": "Realme 16 Pro+",
    "colorNames": [
      "Master Grey",
      "Master Gold",
      "Camellia Pink"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 55999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 60999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 65999,
        "verified": true
      }
    ]
  },
  "realme-16t": {
    "brand": "Realme",
    "name": "Realme 16T",
    "colorNames": [
      "Speed Green",
      "Racing Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "realme-c71": {
    "brand": "Realme",
    "name": "Realme C71",
    "colorNames": [
      "Meadow Green",
      "Twilight Purple"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12869,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14869,
        "verified": true
      }
    ]
  },
  "realme-c83": {
    "brand": "Realme",
    "name": "Realme C83",
    "colorNames": [
      "Meadow Green",
      "Twilight Purple"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 173,
        "verified": true
      }
    ]
  },
  "realme-p3x": {
    "brand": "Realme",
    "name": "Realme P3x",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "realme-p4": {
    "brand": "Realme",
    "name": "Realme P4",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black",
      "Starlight Silver"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "realme-p4-lite": {
    "brand": "Realme",
    "name": "Realme P4 Lite",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 12999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      }
    ]
  },
  "realme-p4-power": {
    "brand": "Realme",
    "name": "Realme P4 Power",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 32999,
        "verified": true
      }
    ]
  },
  "realme-p4x": {
    "brand": "Realme",
    "name": "Realme P4x",
    "colorNames": [
      "Nebula Purple",
      "Cosmic Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 20499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 23499,
        "verified": true
      }
    ]
  },
  "realme-pad-2-lite": {
    "brand": "Realme",
    "name": "Realme Pad 2 Lite",
    "colorNames": [
      "Green",
      "Grey"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 21999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 25999,
        "verified": true
      }
    ]
  },
  "redmi-15a": {
    "brand": "Redmi",
    "name": "Redmi 15A",
    "colorNames": [
      "Light Blue",
      "Black",
      "Green"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 14859,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16859,
        "verified": true
      }
    ]
  },
  "redmi-15c": {
    "brand": "Redmi",
    "name": "Redmi 15C",
    "colorNames": [
      "Stardust Purple",
      "Midnight Black",
      "Forest Green"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      }
    ]
  },
  "redmi-a4": {
    "brand": "Redmi",
    "name": "Redmi A4",
    "colorNames": [
      "Midnight Black",
      "Starlight Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      }
    ]
  },
  "redmi-a5": {
    "brand": "Redmi",
    "name": "Redmi A5",
    "colorNames": [
      "Midnight Black",
      "Lake Blue",
      "Olive Green"
    ],
    "variants": [
      {
        "ram": "3GB",
        "storage": "64GB",
        "price": 8699,
        "verified": true
      },
      {
        "ram": "4GB",
        "storage": "128GB",
        "price": 10699,
        "verified": true
      }
    ]
  },
  "redmi-a7-pro": {
    "brand": "Redmi",
    "name": "Redmi A7 Pro",
    "colorNames": [
      "Midnight Black",
      "Starlight Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 17999,
        "verified": true
      }
    ]
  },
  "samsung-a06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy A06",
    "colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 10738,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 12738,
        "verified": true
      }
    ]
  },
  "samsung-f06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F06",
    "colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15999,
        "verified": true
      }
    ]
  },
  "samsung-f07": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F07",
    "colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 11999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 13999,
        "verified": true
      }
    ]
  },
  "samsung-f36": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F36",
    "colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 25499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28499,
        "verified": true
      }
    ]
  },
  "samsung-f70e": {
    "brand": "Samsung",
    "name": "Samsung Galaxy F70e",
    "colorNames": [
      "Awesome Graphite",
      "Awesome Silver"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 17499,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 20499,
        "verified": true
      }
    ]
  },
  "samsung-m06": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M06",
    "colorNames": [
      "Black",
      "Light Blue",
      "Gold"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 13470,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 15470,
        "verified": true
      }
    ]
  },
  "samsung-m36": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M36",
    "colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 19647,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22647,
        "verified": true
      }
    ]
  },
  "samsung-m56": {
    "brand": "Samsung",
    "name": "Samsung Galaxy M56",
    "colorNames": [
      "Awesome Graphite",
      "Awesome Silver",
      "Awesome Violet"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 25925,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 30925,
        "verified": true
      }
    ]
  },
  "samsung-s25-fe": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S25 FE",
    "colorNames": [
      "Icyblue",
      "Jetblack",
      "Navy",
      "White"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 77999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 84999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "512GB",
        "price": 94999,
        "verified": true
      }
    ]
  },
  "samsung-s25-ultra": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S25 Ultra",
    "colorNames": [
      "Titanium Silverblue",
      "Titanium Black",
      "Titanium Gray",
      "Titanium Whitesilver"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 129990,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 139990,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 159990,
        "verified": true
      }
    ]
  },
  "samsung-s26-plus": {
    "brand": "Samsung",
    "name": "Samsung Galaxy S26+",
    "colorNames": [
      "Black",
      "Cobalt Violet",
      "Sky Blue",
      "White",
      "Pink Gold (Online Exclusive)",
      "Silver Shadow (Online Exclusive)"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 114999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 124999,
        "verified": true
      }
    ]
  },
  "samsung-tab-s10-lite": {
    "brand": "Samsung",
    "name": "Samsung Galaxy Tab S10 Lite",
    "colorNames": [
      "Graphite",
      "Silver",
      "Pink Gold"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 30140,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 35140,
        "verified": true
      }
    ]
  },
  "vivo-t4": {
    "brand": "Vivo",
    "name": "Vivo T4",
    "colorNames": [
      "Emerald Blaze",
      "Phantom Grey"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 28999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 33999,
        "verified": true
      }
    ]
  },
  "vivo-t4-lite": {
    "brand": "Vivo",
    "name": "Vivo T4 Lite",
    "colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 23999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      }
    ]
  },
  "vivo-t4-pro": {
    "brand": "Vivo",
    "name": "Vivo T4 Pro",
    "colorNames": [
      "Nitro Blue",
      "Blaze Gold"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 29999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 34999,
        "verified": true
      }
    ]
  },
  "vivo-t4-ultra": {
    "brand": "Vivo",
    "name": "Vivo T4 Ultra",
    "colorNames": [
      "Phoenix Gold",
      "Meteor Grey"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "vivo-t4r": {
    "brand": "Vivo",
    "name": "Vivo T4R",
    "colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28999,
        "verified": true
      }
    ]
  },
  "vivo-t4x": {
    "brand": "Vivo",
    "name": "Vivo T4x",
    "colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 22999,
        "verified": true
      }
    ]
  },
  "vivo-t5-pro": {
    "brand": "Vivo",
    "name": "Vivo T5 Pro",
    "colorNames": [
      "Glacier Blue",
      "Starry Black",
      "Champagne Gold"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 39999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "vivo-t5x": {
    "brand": "Vivo",
    "name": "Vivo T5x",
    "colorNames": [
      "Glacier Blue",
      "Starry Black"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 24999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 28999,
        "verified": true
      }
    ]
  },
  "vivo-v70": {
    "brand": "Vivo",
    "name": "Vivo V70",
    "colorNames": [
      "Starry Black",
      "Titanium Silver",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 53999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 60999,
        "verified": true
      }
    ]
  },
  "vivo-v70-elite": {
    "brand": "Vivo",
    "name": "Vivo V70 Elite",
    "colorNames": [
      "Starry Black",
      "Titanium Silver",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 58999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 66999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 78999,
        "verified": true
      }
    ]
  },
  "vivo-v70-fe": {
    "brand": "Vivo",
    "name": "Vivo V70 FE",
    "colorNames": [
      "Jade Green",
      "Coral Red"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      }
    ]
  },
  "vivo-y05": {
    "brand": "Vivo",
    "name": "Vivo Y05",
    "colorNames": [
      "Midnight Black",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 14999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      }
    ]
  },
  "vivo-y11": {
    "brand": "Vivo",
    "name": "Vivo Y11",
    "colorNames": [
      "Midnight Black",
      "Ocean Blue",
      "Sunset Orange"
    ],
    "variants": [
      {
        "ram": "4GB",
        "storage": "64GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 18999,
        "verified": true
      }
    ]
  },
  "vivo-y31": {
    "brand": "Vivo",
    "name": "Vivo Y31",
    "colorNames": [
      "Starry Black",
      "Champagne Gold"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 25999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 29999,
        "verified": true
      }
    ]
  },
  "vivo-y51-pro": {
    "brand": "Vivo",
    "name": "Vivo Y51 Pro",
    "colorNames": [
      "Starry Black",
      "Champagne Gold",
      "Ocean Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 33999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 39999,
        "verified": true
      }
    ]
  },
  "iqoo-15": {
    "brand": "iQOO",
    "name": "iQOO 15",
    "colorNames": [
      "Alpha",
      "Legend",
      "Gray",
      "Green",
      "Blue",
      "Apex"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 76999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 86999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "1TB",
        "price": 101999,
        "verified": true
      }
    ]
  },
  "iqoo-15r": {
    "brand": "iQOO",
    "name": "iQOO 15R",
    "colorNames": [
      "Raging Blue",
      "MoonKnight",
      "Titanium"
    ],
    "variants": [
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 49999,
        "verified": true
      }
    ]
  },
  "iqoo-neo-10": {
    "brand": "iQOO",
    "name": "iQOO Neo 10",
    "colorNames": [
      "Inferno Red",
      "Titanium Chrome",
      "Blaze Orange",
      "Onyx Black"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 41999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 46999,
        "verified": true
      },
      {
        "ram": "16GB",
        "storage": "512GB",
        "price": 54999,
        "verified": true
      }
    ]
  },
  "iqoo-z10-lite": {
    "brand": "iQOO",
    "name": "iQOO Z10 Lite",
    "colorNames": [
      "Storm Black",
      "Cyber Blue"
    ],
    "variants": [
      {
        "ram": "6GB",
        "storage": "128GB",
        "price": 16999,
        "verified": true
      },
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 19999,
        "verified": true
      }
    ]
  },
  "iqoo-z10r": {
    "brand": "iQOO",
    "name": "iQOO Z10R",
    "colorNames": [
      "Storm Black",
      "Cyber Blue"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "128GB",
        "price": 22999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "256GB",
        "price": 26999,
        "verified": true
      }
    ]
  },
  "iqoo-z11x": {
    "brand": "iQOO",
    "name": "iQOO Z11x",
    "colorNames": [
      "Storm Black",
      "Cyber Blue",
      "Neon Green"
    ],
    "variants": [
      {
        "ram": "8GB",
        "storage": "256GB",
        "price": 27999,
        "verified": true
      },
      {
        "ram": "12GB",
        "storage": "512GB",
        "price": 32999,
        "verified": true
      }
    ]
  }
};

export const DIRECT_URLS_META = {
  "generatedAt": "2026-07-16T10:41:38.997Z",
  "source": "C:\\Users\\ramak\\Downloads\\products_with_direct_urls.csv",
  "matched": 107,
  "unknown": [],
  "searchUrls": [],
  "totalVariants": 225
};
